import {useState} from 'react';
import {makeId} from '@/lib/classroom';
import * as op from '@/app/w/[token]/features/scores/operations';
import {checked,type useScoresDesignController} from './useScoresDesignController';
import s from './ScoreWorkspaces.module.css';
export function ScoreAnalysisDesign({controller:c}:{controller:ReturnType<typeof useScoresDesignController>}){
 const [paperId,setPaperId]=useState(''),[paperPage,setPaperPage]=useState(1),[file,setFile]=useState<File|null>(null),[upload,setUpload]=useState(false),[page,setPage]=useState(1),[processing,setProcessing]=useState(false);
 const exam=c.exam;if(!exam)return null;
 const papers=exam.paperAnalyses??[],paper=papers.find(p=>p.id===paperId)??papers[0],items=exam.knowledgeItems??[],pages=Math.max(1,Math.ceil(items.length/10)),safePage=Math.min(page,pages),editing=c.editor?.kind==='paper'?c.editor:null;
 const paperPages=Math.max(1,Math.ceil(papers.length/5)),safePaperPage=Math.min(paperPage,paperPages);
 const selectPaper=(id:string)=>{if(c.guard())setPaperId(id);};
 async function preview(){if(!file||!exam||c.locked||processing||!c.guard())return;setProcessing(true);try{await new Promise(r=>setTimeout(r,500));const id=makeId('paper');await c.apply(d=>checked(op.addScorePaperAnalysis(d,c.classId,exam.id,{id,sourceName:file.name,sourceType:file.type,sourceSize:file.size,createdAt:new Date().toISOString(),status:'待核对',message:'合成候选，未上传文件。',items:[{id:makeId('item'),title:'概括段意',questionNo:'4',subject:exam.subjects[0],knowledgePoint:'信息归纳',maxScore:5,scores:{},source:'ai',confidence:.85},{id:makeId('item'),title:'表达观点',questionNo:'5',subject:exam.subjects[0],knowledgePoint:'观点表达',maxScore:5,scores:{},source:'ai',confidence:.8}]})),()=>{setFile(null);setUpload(false);setPaperId(id);});}finally{setProcessing(false);}}
 return <section className={s.workspace} data-analysis-workspace><header className={s.analysisTools}><h2>试卷与知识点</h2><nav><button className="score-primary" disabled={c.locked||processing} onClick={()=>setUpload(!upload)} aria-expanded={upload}>选择试卷</button><button disabled={c.locked||processing} onClick={()=>c.begin('item',{title:'',subject:exam.subjects[0]??'',questionNo:'',knowledgePoint:'',questionType:'',max:'10'})}>人工新增分析项</button></nav></header>
 {upload&&<div className={s.upload}><input aria-label="选择试卷文件" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={c.locked||processing} onChange={ev=>{const f=ev.target.files?.[0];if(!f)return;if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(f.type)||f.size<=0||f.size>12*1024*1024){c.setError('仅支持不超过12MB的JPG、PNG、WEBP或PDF。');setFile(null);return;}setFile(f);c.setError('');}}/><button disabled={!file||c.locked||processing} onClick={()=>void preview()}>{processing?'生成合成候选中…':'预览合成识别结果'}</button><p>隔离预览仅生成合成候选，不上传文件或调用识别服务。</p></div>}
 <div className={s.analysisLayout}><aside className={s.papers}><h3>试卷任务 · {papers.length}份</h3>{papers.slice((safePaperPage-1)*5,safePaperPage*5).map(p=><button className={s.paperChoice} key={p.id} aria-pressed={paper?.id===p.id} onClick={()=>selectPaper(p.id)}><b>{p.sourceName}</b><span>{p.status}{p.status==='待核对'?` · ${p.items?.length??0}项`:''}</span></button>)}{papers.length>5&&<nav aria-label="试卷任务分页"><button disabled={safePaperPage===1} onClick={()=>{if(c.guard())setPaperPage(p=>p-1);}}>上一页试卷</button><span>{safePaperPage}/{paperPages}</span><button disabled={safePaperPage===paperPages} onClick={()=>{if(c.guard())setPaperPage(p=>p+1);}}>下一页试卷</button></nav>}{!papers.length&&<p className={s.note}>暂无试卷任务。可选择文件预览候选，也可直接人工建立分析项。</p>}</aside>
 <section className={s.review}><header><h3>{paper?.sourceName??'核对试卷候选'}</h3>{paper?.status==='待核对'&&<span className={s.warning}>{paper.items?.length??0}项尚未进入统计</span>}</header>
 {!paper?<div className={s.empty}><p>先核对题目与分值，确认后才进入统计。</p></div>:paper.status==='失败'?<div className={s.empty} role="status"><h3>本次识别未完成</h3><p>{paper.message}</p><button onClick={()=>setUpload(true)}>重新选择文件</button><button disabled={c.locked} onClick={()=>c.begin('item',{title:'',subject:exam.subjects[0],max:'10'})}>改为人工新增</button></div>:<>
 <p className={s.note}>{paper.status==='待核对'?'以下候选需人工核对，不代表已经确认。':'该试卷已处理，已确认项目见下方台账。'}</p>
 {(editing?.fields.id===paper.id?editing.items:c.mobile?[]:paper.items)?.map((item,index)=><div className={s.candidate} key={item.id}>{(['questionNo','title','knowledgePoint','maxScore'] as const).map(key=><label key={key}>{key==='questionNo'?'题号':key==='title'?'分析项':key==='knowledgePoint'?'知识点':'满分'}{editing?.fields.id===paper.id?<input disabled={c.locked} type={key==='maxScore'?'number':'text'} value={item[key]??''} onChange={ev=>c.setEditor({...editing,items:editing.items!.map((it,i)=>i===index?{...it,[key]:key==='maxScore'?Number(ev.target.value):ev.target.value}:it)})}/>:<b>{item[key]||'未填写'}</b>}</label>)}</div>)}
 {paper.status==='待核对'&&<footer>{editing?.fields.id===paper.id?<><button disabled={c.busy} onClick={c.closeEditor}>取消核对</button><button className="score-primary" disabled={c.readOnly||c.busy||!(editing.items?.length)} onClick={()=>void c.saveEditor()}>{c.pending?'重试同步':'确认并加入统计'}</button></>:<button disabled={c.locked||!(paper.items?.length)} onClick={()=>c.begin('paper',{id:paper.id},structuredClone(paper.items??[]))}>核对候选</button>}</footer>}</>}
 </section></div>
 <section className={s.items}><h2>本次考试 · 已确认分析项</h2>{!items.length&&<div className={s.empty}><h3>还没有已确认分析项</h3><p>人工新增，或核对试卷候选后加入；未确认内容不生成统计图。</p></div>}{items.slice((safePage-1)*10,safePage*10).map(item=>{const values=c.students.map(st=>item.scores[st.id]).filter(v=>v!=null),rate=values.length&&item.maxScore>0?Math.round(values.reduce((a,b)=>a+b,0)/values.length/item.maxScore*100):null;return <article className={s.itemRow} data-analysis-item={item.id} key={item.id}><div><h3>{item.title}</h3><p>{item.subject} · {item.knowledgePoint||'未标注知识点'} · 满分{item.maxScore}</p></div><div className={s.itemRate}><small>得分率</small><strong>{rate==null?'未录入':`${rate}%`}</strong><div className={s.meter} aria-hidden="true"><span style={{width:`${rate??0}%`}}/></div></div><div><small>已录入</small><p>{values.length}/{c.students.length}人</p></div><nav><button disabled={c.locked} onClick={()=>c.begin('item-scores',{id:item.id,...Object.fromEntries(c.students.map(st=>[st.id,String(item.scores[st.id]??'')]))})}>录入分数</button><button disabled={c.locked} onClick={()=>c.setDeleteTarget({kind:'item',id:item.id,title:item.title})}>删除</button></nav></article>})}{items.length>10&&<footer><button disabled={safePage===1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{safePage}/{pages}</span><button disabled={safePage===pages} onClick={()=>setPage(p=>p+1)}>下一页</button></footer>}<p className={s.note}>得分率仅统计已录入学生，未录入不按零分计算；请结合题目难度与录入覆盖判断。</p></section>
 </section>;
}
