import {useState} from 'react';
import {ThemeBoundary} from '@/app/components/workbench/theme/ThemeBoundary';
import {Dialog} from '@/app/components/workbench/ui/Dialog';
import {CampusIcon} from '@/app/components/campus/primitives';
import {makeId} from '@/lib/classroom';
import * as op from '@/app/w/[token]/features/scores/operations';
import {ScoreTrendsDesign} from './ScoreTrendsDesign';
import {maxFor,scoreKey,checked,type useScoresDesignController} from './useScoresDesignController';
import art from './stationery-p01.png';
import s from './ScoresDesign.module.css';
type C=ReturnType<typeof useScoresDesignController>;
export function ScoresDesign({controller:c}:{controller:C}){
 const [filters,setFilters]=useState(false),[library,setLibrary]=useState(false),[examQuery,setExamQuery]=useState(''),[examYear,setExamYear]=useState('全部'),[examSubject,setExamSubject]=useState('全部'),[examSort,setExamSort]=useState('新到旧'),[examPage,setExamPage]=useState(1),[replace,setReplace]=useState(false),[selectedFile,setSelectedFile]=useState<File|null>(null),[itemPage,setItemPage]=useState(1),[reflections,setReflections]=useState('');
 const e=c.editor,exam=c.exam,fields=e?.fields??{},totalMax=exam?c.subjects.reduce((n,sub)=>n+maxFor(exam,sub),0):0;
 const entryCount=exam?op.scoreEntryCount(exam,c.students):0,complete=c.students.filter(st=>c.summary(st).complete).length;
 const exams=c.exams.filter(ex=>(`${ex.title} ${ex.date} ${ex.subjects.join(' ')}`.includes(examQuery.trim()))&&(examYear==='全部'||ex.date.startsWith(examYear))&&(examSubject==='全部'||ex.subjects.includes(examSubject))).sort((a,b)=>examSort==='新到旧'?b.date.localeCompare(a.date):a.date.localeCompare(b.date)),examPages=Math.max(1,Math.ceil(exams.length/10));
 const input=(label:string,key:string,type='text')=><label>{label}<input aria-label={label} type={type} value={fields[key]??''} onChange={ev=>c.setField(key,ev.target.value)}/></label>;
 const select=(label:string,key:string,options:string[])=><label>{label}<select aria-label={label} value={fields[key]??''} onChange={ev=>c.setField(key,ev.target.value)}>{options.map(v=><option key={v} value={v}>{v||'未设置'}</option>)}</select></label>;
 const recovery=<>{c.error&&<p role="alert" className={s.error}>{c.error}</p>}{c.pending&&<div className={s.recovery}><span>本机改动待同步，重试不会重复新增。</span><button disabled={c.busy} onClick={()=>void c.sync()}>重试同步</button>{c.conflict&&<><button onClick={c.exportDraft}>导出草稿</button><button onClick={()=>setReplace(true)}>载入最新数据</button></>}</div>}</>;
 const openRanges=()=>{if(!exam)return;const sub=c.subjects.includes(c.subject)?c.subject:'__total',max=sub==='__total'?totalMax:maxFor(exam,sub);c.begin('ranges',{subject:sub,max:String(max),ranges:JSON.stringify(exam.scoreRanges?.[sub]??[{id:'pass',label:'60%以上',min:Math.ceil(max*.6),max}])});};
 const toggled=(id:string)=>c.setSelected(ids=>ids.includes(id)?ids.filter(v=>v!==id):[...ids,id]);
 const editorTitle=e?.kind==='exam'?(fields.id?'编辑考试':'新增考试'):e?.kind==='student'?'学生本次成绩':e?.kind==='batch'?'批量录分':e?.kind==='ranges'?'满分与分数区间':e?.kind==='item'?'新增分析项':e?.kind==='paper'?'核对试卷候选':'分析项录分';
 async function syntheticPaper(){if(!selectedFile||!exam)return;const id=makeId('paper'),itemId=makeId('item');await c.apply(d=>checked(op.addScorePaperAnalysis(d,c.classId,exam.id,{id,sourceName:selectedFile.name,sourceType:selectedFile.type,sourceSize:selectedFile.size,createdAt:new Date().toISOString(),status:'待核对',message:'合成识别结果，仅用于设计预览，未上传文件。',items:[{id:itemId,title:'合成阅读分析项',questionNo:'1',subject:exam.subjects[0],knowledgePoint:'信息提取',maxScore:10,scores:{},source:'ai',confidence:.85}]})),()=>setSelectedFile(null));}
 return <main className={s.page} data-scores-design="page"><header className={s.heading}><div><h1>成绩分析</h1><p>按考试记录分数，结合录入情况分析。</p></div><img src={typeof art==='string'?art:art.src} width="1536" height="1024" alt=""/></header>
 <section className={s.examBand}><div><h2>{exam?`${c.mobile?'':'当前考试 · '}${exam.title}`:'尚未建立考试'}</h2><p>{exam?`${exam.date} · ${c.subjects.map(sub=>`${sub} ${maxFor(exam,sub)}分`).join(' / ')}`:'从一次具体考试开始记录。'}</p></div><nav><button disabled={!exam||c.busy} onClick={()=>{if(c.guard())setLibrary(true);}}>切换考试</button><button disabled={c.locked||!exam} onClick={()=>c.openExam(true)}>编辑</button><button className={s.primary} disabled={c.locked||!c.students.length} onClick={()=>c.openExam()}>新增考试</button></nav></section>
 {exam&&<nav className={s.tabs} aria-label="成绩工作区">{[['records',c.mobile?'录分':'成绩录入'],['trends',c.mobile?'趋势':'历次趋势'],['analysis',c.mobile?'试卷分析':'试卷与知识点']].map(([id,label])=><button key={id} aria-pressed={c.tab===id} onClick={()=>c.switchTab(id)}>{label}</button>)}</nav>}
 {c.message&&<p className={s.message} role="status">{c.message}<button onClick={()=>c.setMessage('')}>关闭提示</button></p>}{!e&&recovery}
 {Object.keys(c.draftScores).length>0&&<div className={s.saveBar}><span>{Object.keys(c.draftScores).length}项分数尚未保存</span><button className={s.primary} disabled={c.busy} onClick={()=>void c.saveScores()}>{c.pending?'重试同步':'保存录分'}</button><button disabled={c.pending||c.busy} onClick={()=>c.setConfirmClose(true)}>放弃录分</button></div>}
 {!exam&&<div className={s.empty}><h2>{c.students.length?'还没有考试记录':'先建立学生名单'}</h2><p>新考试的成绩保持空白，录入0分后才按0分统计。</p></div>}
 {exam&&c.tab==='records'&&<><div className={s.toolbar}><p>已录<strong>{entryCount}/{c.students.length*c.subjects.length}</strong>项 · {complete}人已录全 · {c.students.length-complete}人待补全</p><label className={s.search}><CampusIcon name="search"/><input aria-label="搜索成绩学生" placeholder="搜索姓名或学号" value={c.query} onChange={ev=>{c.setQuery(ev.target.value);c.setPage(1);}}/></label><select aria-label="显示科目" value={c.subject} onChange={ev=>{c.setSubject(ev.target.value);c.setRange('全部');c.setPage(1);}}>{['全部',...c.subjects].map(sub=><option key={sub}>{sub}</option>)}</select><button aria-expanded={filters} onClick={()=>setFilters(!filters)}>{c.mobile?'筛选':'更多筛选'}</button></div>
 {filters&&<div className={s.filters}><label>小组<select value={c.group} onChange={ev=>{c.setGroup(ev.target.value);c.setPage(1);}}>{['全部',...new Set(c.students.map(st=>String(st.group)))].map(v=><option key={v}>{v}</option>)}</select></label><label>本次跟进<select value={c.follow} onChange={ev=>{c.setFollow(ev.target.value);c.setPage(1);}}>{['全部','已标记','未标记'].map(v=><option key={v}>{v}</option>)}</select></label><label>分数区间<select value={c.range} onChange={ev=>{c.setRange(ev.target.value);c.setPage(1);}}><option>全部</option>{c.ranges.map(r=><option key={r.id} value={r.id}>{r.label} {r.min}–{r.max}</option>)}</select></label><label>排序<select value={c.sort} onChange={ev=>c.setSort(ev.target.value)}>{['待处理优先','学号','姓名','总分降序','原始平均降序',...c.subjects.map(sub=>'科目:'+sub)].map(v=><option key={v}>{v}</option>)}</select></label><button disabled={c.locked} onClick={openRanges}>满分与区间</button><button onClick={c.reset}>重置筛选</button></div>}
 <div className={s.selection}><label><input type="checkbox" aria-label="选择当前页" disabled={c.locked} checked={!!c.pagedRows.length&&c.pagedRows.every(st=>c.selected.includes(st.id))} onChange={ev=>c.setSelected(ids=>ev.target.checked?[...new Set([...ids,...c.pagedRows.map(st=>st.id)])]:ids.filter(id=>!c.pagedRows.some(st=>st.id===id)))}/> {c.mobile?'批量选择':'选择当前页'}</label><span>共{c.rows.length}人{c.selected.length?` · 已选${c.selected.length}人`:''}</span>{c.selected.length>0&&<><button className={s.primary} disabled={c.locked} onClick={()=>c.begin('batch',{subject:c.shownSubjects[0],value:''})}>批量录分</button><button onClick={()=>c.setSelected([])}>取消选择</button></>}</div>
 {!c.mobile?<div className={s.tableScroll}><table><thead><tr><th>选择</th><th>学生</th>{c.shownSubjects.map(sub=><th key={sub}>{sub} <small>/{maxFor(exam,sub)}</small></th>)}<th>总分 <small>/{totalMax}</small></th><th>本次跟进</th><th>操作</th></tr></thead><tbody>{c.pagedRows.map(st=><tr key={st.id} data-score-row={st.id}><td><input type="checkbox" aria-label={`选择${st.name}`} checked={c.selected.includes(st.id)} disabled={c.locked} onChange={()=>toggled(st.id)}/></td><th scope="row">{st.name}<small>学号{st.studentNo}</small></th>{c.shownSubjects.map(sub=><td key={sub}><input className={op.scoreEntry(exam,st.id,sub)==null?s.missing:''} aria-label={`${st.name} ${sub}分数`} inputMode="decimal" disabled={c.locked} value={c.draftScores[scoreKey(st.id,sub)]??String(op.scoreEntry(exam,st.id,sub)??'')} placeholder="未录入" onChange={ev=>c.stageScore(st,sub,ev.target.value)}/></td>)}<td>{c.summary(st).total??'待补全'}</td><td><button disabled={c.locked} className={exam.followUpStudentIds?.includes(st.id)?s.marked:''} onClick={()=>void c.toggleFollow(st.id)}>{exam.followUpStudentIds?.includes(st.id)?'已标记':'未标记'}</button></td><td><button onClick={()=>c.openStudent(st)} disabled={c.busy||c.pending}>详情</button></td></tr>)}</tbody></table></div>:<div className={s.mobileRows}>{c.pagedRows.map(st=><article data-score-row={st.id} key={st.id}><header><label>{c.selected.length>0&&<input type="checkbox" aria-label={`选择${st.name}`} checked={c.selected.includes(st.id)} disabled={c.locked} onChange={()=>toggled(st.id)}/>}<b>{st.name}</b></label>{!c.summary(st).complete&&<span className={s.missing}>待补全</span>}{exam.followUpStudentIds?.includes(st.id)&&<span className={s.marked}>本次已标记</span>}<button onClick={()=>c.openStudent(st)} disabled={c.busy||c.pending}>{c.summary(st).complete?'详情':'录分'} ›</button></header><p>学号{st.studentNo} · 第{st.group}组</p><div className={s.mobileScores}>{c.shownSubjects.map(sub=><span key={sub}><small>{sub} /{maxFor(exam,sub)}</small><strong>{op.scoreEntry(exam,st.id,sub)??'未录入'}</strong></span>)}{c.summary(st).complete&&<span><small>总分 /{totalMax}</small><strong>{c.summary(st).total}</strong></span>}</div></article>)}</div>}
 {!c.rows.length&&<p className={s.empty}>没有匹配的学生。<button onClick={c.reset}>清除筛选</button></p>}<footer className={s.pagination}><span>空白表示未录入，0分计入统计。</span><button disabled={c.safePage===1} onClick={()=>c.setPage(p=>p-1)}>上一页</button><b>{c.safePage}/{c.pages}</b><button disabled={c.safePage===c.pages} onClick={()=>c.setPage(p=>p+1)}>下一页</button></footer></>}
 {exam&&c.tab==='trends'&&<div className={s.subpage}><p className={s.scopeNote}>科目条件用于筛选包含该科的考试；得分率仍按每场所有已录科目计算。缺失记录不按0分连线。</p><ScoreTrendsDesign data={c.data} classId={c.classId}/></div>}
 {exam&&c.tab==='analysis'&&<div className={s.analysis}><header><h2>试卷与知识点分析</h2><button className={s.primary} disabled={c.locked} onClick={()=>c.begin('item',{title:'',subject:exam.subjects[0]??'',questionNo:'',knowledgePoint:'',questionType:'',max:'10'})}>人工新增分析项</button></header><p>先核对题目与分值，确认后才进入统计。</p><div className={s.upload}><label>选择试卷<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={c.locked} onChange={ev=>{const file=ev.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)||file.size<=0||file.size>12*1024*1024){c.setError('仅支持不超过12MB的JPG、PNG、WEBP或PDF。');setSelectedFile(null);return;}setSelectedFile(file);c.setError('');}}/></label><button disabled={c.locked||!selectedFile} onClick={()=>void syntheticPaper()}>预览合成识别结果</button><small>隔离预览不上传文件，以下AI内容为合成候选。</small></div>
 {(exam.paperAnalyses??[]).map(paper=><article className={s.paper} key={paper.id}><div><h3>{paper.sourceName}</h3><p>{paper.status} · {paper.message??'先核对题号、知识点与分值'}</p></div>{paper.status==='待核对'&&<button disabled={c.locked} onClick={()=>c.begin('paper',{id:paper.id},structuredClone(paper.items??[]))}>核对候选</button>}{paper.status==='失败'&&<span>请重新选择文件后预览</span>}</article>)}
 <h2>已确认分析项</h2>{!(exam.knowledgeItems??[]).length&&<p className={s.empty}>暂无已确认分析项。可人工建立，或核对候选后加入。</p>}{(exam.knowledgeItems??[]).slice((Math.min(itemPage,Math.max(1,Math.ceil((exam.knowledgeItems??[]).length/10)))-1)*10,Math.min(itemPage,Math.max(1,Math.ceil((exam.knowledgeItems??[]).length/10)))*10).map(item=>{const values=c.students.map(st=>item.scores[st.id]).filter(v=>v!=null),rate=values.length?Math.round(values.reduce((a,b)=>a+b,0)/values.length/item.maxScore*100):null;return <article className={s.item} key={item.id}><div><h3>{item.questionNo?`${item.questionNo}. `:''}{item.title}</h3><p>{item.subject} · {item.knowledgePoint||'未标注知识点'} · 满分{item.maxScore}分</p><small>{values.length}/{c.students.length}人已录 · {item.source==='ai'?'已核对候选':'人工建立'}</small></div><strong>{rate==null?'未录入':`${rate}%`}</strong><button disabled={c.locked} onClick={()=>c.begin('item-scores',{id:item.id,...Object.fromEntries(c.students.map(st=>[st.id,String(item.scores[st.id]??'')]))})}>录入分数</button><button disabled={c.locked} onClick={()=>c.setDeleteTarget({kind:'item',id:item.id,title:item.title})}>删除</button></article>;})}{(exam.knowledgeItems??[]).length>10&&<nav className={s.pagination}><button disabled={itemPage===1} onClick={()=>setItemPage(p=>p-1)}>上一页</button><span>{itemPage}/{Math.ceil(exam.knowledgeItems!.length/10)}</span><button disabled={itemPage*10>=exam.knowledgeItems!.length} onClick={()=>setItemPage(p=>p+1)}>下一页</button></nav>}<p className={s.scopeNote}>仅按已录学生计算该分析项得分率，请结合难度、缺考与录入覆盖率判断。</p></div>}
 <ThemeBoundary><Dialog open={library} title="切换考试" onRequestClose={()=>setLibrary(false)}><div className={s.form}><label>搜索考试<input value={examQuery} onChange={ev=>{setExamQuery(ev.target.value);setExamPage(1);}}/></label><label>年月<input placeholder="全部或2026-09" value={examYear==='全部'?'':examYear} onChange={ev=>{setExamYear(ev.target.value||'全部');setExamPage(1);}}/></label><label>科目<select value={examSubject} onChange={ev=>{setExamSubject(ev.target.value);setExamPage(1);}}>{['全部',...new Set(c.exams.flatMap(ex=>ex.subjects))].map(v=><option key={v}>{v}</option>)}</select></label><label>排序<select value={examSort} onChange={ev=>setExamSort(ev.target.value)}><option>新到旧</option><option>旧到新</option></select></label>{exams.slice((Math.min(examPage,examPages)-1)*10,Math.min(examPage,examPages)*10).map(ex=><button key={ex.id} onClick={()=>{c.switchExam(ex.id);setLibrary(false);}}>{ex.title} · {ex.date} · {ex.subjects.join(' / ')}</button>)}{!exams.length&&<p>没有匹配的考试。</p>}<nav className={s.pagination}><button disabled={examPage===1} onClick={()=>setExamPage(p=>p-1)}>上一页</button><span>{Math.min(examPage,examPages)}/{examPages}</span><button disabled={examPage>=examPages} onClick={()=>setExamPage(p=>p+1)}>下一页</button></nav></div></Dialog>
 {e&&<Dialog open title={editorTitle} busy={c.busy} dirty={c.dirty} onRequestClose={c.closeEditor} footer={<><button disabled={c.busy} onClick={c.closeEditor}>取消</button>{e.kind==='exam'&&fields.id&&<button disabled={c.locked} onClick={()=>c.setDeleteTarget({kind:'exam',id:fields.id,title:fields.title})}>删除考试</button>}<button className={s.primary} disabled={c.readOnly||c.busy} onClick={()=>void c.saveEditor()}>{c.busy?'保存中…':c.pending?'重试同步':e.kind==='paper'?'确认并加入统计':'保存'}</button></>}>{recovery}<fieldset disabled={c.locked} className={s.form}>
 {e.kind==='exam'&&<>{input('考试名称','title')}{input('考试日期','date')}{input('科目（逗号分隔）','subjects')}<p>删除科目会移除该科已录成绩，保存前请确认。</p></>}
 {e.kind==='student'&&<><h3>{c.students.find(st=>st.id===fields.studentId)?.name} · {exam?.title}</h3>{c.subjects.map(sub=><div key={sub}>{input(`${sub}分数（满分${maxFor(exam!,sub)}）`,'score:'+sub)}</div>)}<p>本次原始平均：{exam?op.studentScoreSummary(exam,fields.studentId).average??'未录入':'未录入'}。原始平均不代表跨满分比较或长期评价。</p><label>本次建议<textarea value={fields.advice} onChange={ev=>c.setField('advice',ev.target.value)}/></label>{select('本次关注科目','focusSubject',['',...c.subjects])}{select('原有等级记录','level',['','优秀','临界','帮扶'])}<button onClick={()=>setReflections(fields.studentId)}>查看关联反思</button><label>本次重点跟进<input type="checkbox" checked={fields.follow==='true'} onChange={ev=>c.setField('follow',String(ev.target.checked))}/></label></>}
 {e.kind==='batch'&&<><p>当前选择{c.selected.length}人；留空保存表示清除该科成绩。</p>{select('批量科目','subject',c.subjects)}{input('批量分数','value')}</>}
 {e.kind==='ranges'&&<><p>{fields.subject==='__total'?'总分分段':fields.subject+'分段'}</p>{fields.subject!=='__total'&&input('满分','max','number')}{(JSON.parse(fields.ranges) as {id:string;label:string;min:number;max:number}[]).map((r,index)=><div className={s.rangeRow} key={r.id}>{(['label','min','max'] as const).map(key=><label key={key}>{key==='label'?'名称':key==='min'?'下限':'上限'}<input value={r[key]} type={key==='label'?'text':'number'} onChange={ev=>{const rows=JSON.parse(fields.ranges);rows[index][key]=key==='label'?ev.target.value:Number(ev.target.value);c.setField('ranges',JSON.stringify(rows));}}/></label>)}<button onClick={()=>c.setField('ranges',JSON.stringify(JSON.parse(fields.ranges).filter((_:unknown,i:number)=>i!==index)))}>移除</button></div>)}<button onClick={()=>c.setField('ranges',JSON.stringify([...JSON.parse(fields.ranges),{id:makeId('range'),label:'新分段',min:0,max:Number(fields.max)}]))}>添加分段</button></>}
 {e.kind==='item'&&<>{input('分析项名称','title')}{input('题号','questionNo')}{select('科目','subject',['',...c.subjects])}{input('知识点','knowledgePoint')}{input('题型','questionType')}{input('满分','max','number')}</>}
 {e.kind==='item-scores'&&<><p>空白是未录入，0分计入统计。</p>{c.students.map(st=><div key={st.id}>{input(st.name+' 分数',st.id)}</div>)}</>}
 {e.kind==='paper'&&<><p>只有确认后的项目进入统计。</p>{e.items?.map((item,index)=><div className={s.paperFields} key={item.id}>{(['questionNo','title','knowledgePoint','maxScore'] as const).map(key=><label key={key}>{key==='questionNo'?'题号':key==='title'?'分析项':key==='knowledgePoint'?'知识点':'满分'}<input value={item[key]??''} type={key==='maxScore'?'number':'text'} onChange={ev=>c.setEditor({...e,items:e.items!.map((it,i)=>i===index?{...it,[key]:key==='maxScore'?Number(ev.target.value):ev.target.value}:it)})}/></label>)}<small>AI置信度{Math.round((item.confidence??0)*100)}% · 需人工核对</small></div>)}</>}
 </fieldset></Dialog>}
 <Dialog open={!!reflections} title="本次关联反思" onRequestClose={()=>setReflections('')}><div className={s.form}>{(c.data.examReflections??[]).filter(r=>r.studentId===reflections&&r.examId===exam?.id&&(!r.classId||r.classId===c.classId)).map(r=><article key={r.id}><h3>{r.date} · {r.status}</h3><p>{r.problem}</p><p>{r.reason}</p><p>{r.action}</p><p>{r.familyMessage}</p><p>{r.teacherNote}</p></article>)}{!(c.data.examReflections??[]).some(r=>r.studentId===reflections&&r.examId===exam?.id)&&<p>本次尚无关联反思；反思页面尚待独立设计。</p>}</div></Dialog>
 <Dialog open={c.confirmClose} title={c.pending?'还有待同步改动':'有未保存改动'} onRequestClose={()=>c.setConfirmClose(false)} footer={<><button onClick={()=>c.setConfirmClose(false)}>继续处理</button>{!c.pending&&!c.busy&&<button onClick={c.discard}>放弃改动</button>}</>}><p>{c.pending?'请先完成同步或导出草稿；重试不会重复新增。':'请先保存或放弃本次输入，再切换考试或工作区。'}</p></Dialog>
 <Dialog open={!!c.deleteTarget} title="确认删除" onRequestClose={()=>{if(!c.pending)c.setDeleteTarget(null);}} footer={<><button disabled={c.pending||c.busy} onClick={()=>c.setDeleteTarget(null)}>取消删除</button><button disabled={c.locked} onClick={()=>void c.remove()}>确认删除</button></>}>{recovery}<p>{c.deleteTarget?.title}将被删除。{c.deleteTarget?.kind==='exam'?'该考试成绩、分析及关联反思也会删除。':''}</p></Dialog>
 <Dialog open={replace} title="载入最新数据？" onRequestClose={()=>setReplace(false)} footer={<><button onClick={()=>setReplace(false)}>保留本机草稿</button><button onClick={c.replaceLatest}>确认载入最新</button></>}><p>将替换本机改动，请先导出需要保留的草稿。</p></Dialog></ThemeBoundary></main>;
}
