import {useEffect,useRef,useState} from 'react';
import {makeId,type ClassroomData,type ScoreExam,type ScoreKnowledgeItem,type Student} from '@/lib/classroom';
import * as op from '@/app/w/[token]/features/scores/operations';
export const scoreKey=(id:string,subject:string)=>JSON.stringify([id,subject]);
export const maxFor=(exam:ScoreExam,subject:string)=>Math.max(1,exam.subjectMaxScores?.[subject]??100);
export const checked=(r:{data?:ClassroomData;error?:string})=>{if(r.error||!r.data)throw Error(r.error||'操作未完成');return r.data;};
type Editor={kind:'exam'|'student'|'batch'|'ranges'|'item'|'item-scores'|'paper';fields:Record<string,string>;items?:ScoreKnowledgeItem[];classId:string;examId:string};
type Props={data:ClassroomData;update:(fn:(d:ClassroomData)=>ClassroomData)=>void;save:()=>Promise<boolean>;readOnly:boolean;mobile:boolean;conflict?:boolean;exportDraft:()=>void;loadLatest:()=>void};
export function useScoresDesignController({data,update,save,readOnly,mobile,conflict=false,exportDraft,loadLatest}:Props){
 const classId=data.activeClassId??data.rosterClasses?.[0]?.id??'',students=data.rosterClasses?.find(c=>c.id===classId)?.students??data.students,exams=op.scoreExamsForClass(data,classId);
 const [examId,setExamId]=useState(''),[tab,setTab]=useState('records'),[query,setQuery]=useState(''),[subject,setSubject]=useState('全部'),[group,setGroup]=useState('全部'),[follow,setFollow]=useState('全部'),[range,setRange]=useState('全部'),[sort,setSort]=useState('待处理优先'),[page,setPage]=useState(1),[selected,setSelected]=useState<string[]>([]),[draftScores,setDraftScores]=useState<Record<string,string>>({});
 const [editor,setEditor]=useState<Editor|null>(null),[baseline,setBaseline]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(false),[confirmClose,setConfirmClose]=useState(false),[deleteTarget,setDeleteTarget]=useState<{kind:'exam'|'item';id:string;title:string}|null>(null);
 const busyRef=useRef(false),pendingRef=useRef<{classId:string;done:()=>void}|null>(null),leave=useRef(false);
 const exam=exams.find(e=>e.id===examId)??exams[0],subjects=exam?.subjects??[],shownSubjects=subjects.includes(subject)?[subject]:subjects;
 const summary=(s:Student)=>exam?op.studentScoreSummary(exam,s.id):{enteredCount:0,complete:false,total:null,average:null,weakSubject:null};
 const ranges=exam?.scoreRanges?.[subjects.includes(subject)?subject:'__total']??[];
 const rows=students.filter(s=>{const info=summary(s),r=ranges.find(r=>r.id===range),value=exam?(subjects.includes(subject)?op.scoreEntry(exam,s.id,subject):info.total):null;return(`${s.name} ${s.studentNo??''} ${exam?.advice?.[s.id]??''}`.includes(query.trim()))&&(group==='全部'||s.group===Number(group))&&(follow==='全部'||(follow==='已标记')===!!exam?.followUpStudentIds?.includes(s.id))&&(!r||(value!=null&&value>=r.min&&value<=r.max));}).sort((a,b)=>{const x=summary(a),y=summary(b);if(sort==='总分降序')return(y.total??-1)-(x.total??-1);if(sort==='原始平均降序')return(y.average??-1)-(x.average??-1);if(sort==='姓名')return a.name.localeCompare(b.name,'zh');if(sort.startsWith('科目:')&&exam)return(op.scoreEntry(exam,b.id,sort.slice(3))??-1)-(op.scoreEntry(exam,a.id,sort.slice(3))??-1);if(sort==='待处理优先'){const priority=(s:Student)=>!summary(s).complete?0:exam?.followUpStudentIds?.includes(s.id)?1:2;const diff=priority(a)-priority(b);if(diff)return diff;}return String(a.studentNo??'').localeCompare(String(b.studentNo??''),'zh',{numeric:true});});
 const pages=Math.max(1,Math.ceil(rows.length/10)),safePage=Math.min(page,pages),editorDirty=!!editor&&JSON.stringify(editor)!==baseline,dirty=editorDirty||Object.keys(draftScores).length>0,locked=readOnly||busy||pending;
 const reset=()=>{setQuery('');setSubject('全部');setGroup('全部');setFollow('全部');setRange('全部');setSort('待处理优先');setPage(1);};
 function guard(){if(dirty||pendingRef.current||busyRef.current){setConfirmClose(true);return false;}return true;}
 function switchExam(id:string){if(!guard())return;setExamId(id);setSelected([]);setEditor(null);reset();}
 function switchTab(value:string){if(guard())setTab(value);}
 async function sync(){if(readOnly||busyRef.current||!pendingRef.current)return false;if(pendingRef.current.classId!==classId){setError('班级已变化，请返回原班级处理待同步改动。');return false;}busyRef.current=true;setBusy(true);setError('');try{if(!await save()){setError('同步失败，改动仍在本机。请重试同步，不会重复新增。');return false;}const done=pendingRef.current.done;pendingRef.current=null;setPending(false);done();setConfirmClose(false);setMessage('改动已保存');return true;}catch{setError('保存连接中断，改动仍在本机，请重试同步。');return false;}finally{busyRef.current=false;setBusy(false);}}
 async function apply(recipe:(d:ClassroomData)=>ClassroomData,done:()=>void=()=>{}){if(locked||busyRef.current||pendingRef.current)return;try{recipe(data);}catch(e){setError(e instanceof Error?e.message:'操作失败');return;}pendingRef.current={classId,done};setPending(true);update(recipe);await sync();}
 function begin(kind:Editor['kind'],fields:Record<string,string>,items?:ScoreKnowledgeItem[]){if((locked&&!(readOnly&&!busy&&!pending&&kind==='student'))||!guard())return;const next={kind,fields,items,classId,examId:exam?.id??''};setEditor(next);setBaseline(JSON.stringify(next));setError('');}
 function openExam(edit=false){begin('exam',{id:edit?exam?.id??'':'',title:edit?exam?.title??'':'',date:edit?exam?.date??'':op.localScoreDate(),subjects:edit?subjects.join('，'):'语文，数学，英语'});}
 function openStudent(s:Student){if(!exam)return;begin('student',{studentId:s.id,follow:String(!!exam.followUpStudentIds?.includes(s.id)),advice:exam.advice?.[s.id]??'',focusSubject:exam.focusSubjects?.[s.id]??'',level:exam.levels?.[s.id]??'',...Object.fromEntries(subjects.map(sub=>['score:'+sub,String(op.scoreEntry(exam,s.id,sub)??'')]))});}
 function setField(key:string,value:string){if(editor&&!locked)setEditor({...editor,fields:{...editor.fields,[key]:value}});}
 function closeEditor(){if(busyRef.current)return;if(editorDirty||pendingRef.current){setConfirmClose(true);return;}setEditor(null);setError('');}
 function discard(){if(pendingRef.current||busyRef.current)return;setEditor(null);setDraftScores({});setConfirmClose(false);setError('');}
 function stageScore(s:Student,sub:string,value:string){if(locked||!exam)return;const key=scoreKey(s.id,sub);setDraftScores(d=>{const next={...d};if(value===String(op.scoreEntry(exam,s.id,sub)??''))delete next[key];else next[key]=value;return next;});}
 function validValue(text:string,max:number){if(!text.trim())return null;const n=Number(text);if(!Number.isFinite(n)||n<0||n>max)throw Error(`分数须在0到${max}之间；留空表示未录入。`);return n;}
 async function saveScores(){if(pendingRef.current){await sync();return;}if(!exam)return;const entries=Object.entries(draftScores);if(!entries.length)return;await apply(d=>entries.reduce((cur,[key,text])=>{const [id,sub]=JSON.parse(key);return checked(op.setScoreEntries(cur,classId,exam.id,[id],sub,validValue(text,maxFor(exam,sub))));},d),()=>setDraftScores({}));}
 async function saveEditor(){if(pendingRef.current){await sync();return;}if(!editor)return;if(editor.classId!==classId||editor.examId!==(exam?.id??'')){setError('考试或班级已变化，请返回原记录处理草稿。');return;}const f=editor.fields,id=makeId('score');const done=()=>{setEditor(null);setSelected([]);};
 await apply(d=>{switch(editor.kind){case'exam':{const draft={title:f.title,date:f.date,subjects:f.subjects.split(/[,，、\n]/)};return checked(f.id?op.editScoreExam(d,classId,f.id,draft):op.createScoreExam(d,classId,draft,()=>id));}case'student':{if(!exam)return d;let next=subjects.reduce((cur,sub)=>checked(op.setScoreEntries(cur,classId,exam.id,[f.studentId],sub,validValue(f['score:'+sub],maxFor(exam,sub)))),d);next=op.patchScoreExam(next,classId,exam.id,{advice:{...exam.advice,[f.studentId]:f.advice},focusSubjects:{...exam.focusSubjects,[f.studentId]:f.focusSubject},followUpStudentIds:f.follow==='true'?[...new Set([...(exam.followUpStudentIds??[]),f.studentId])]:(exam.followUpStudentIds??[]).filter(id=>id!==f.studentId),levels:Object.fromEntries(Object.entries({...exam.levels,[f.studentId]:f.level}).filter(([,v])=>!!v)) as ScoreExam['levels']});return next;}case'batch':{if(!exam)return d;return checked(op.setScoreEntries(d,classId,exam.id,selected,f.subject,validValue(f.value,maxFor(exam,f.subject))));}case'ranges':{if(!exam)return d;const max=Number(f.max);if(!Number.isFinite(max)||max<=0)throw Error('满分必须大于0。');if(f.subject!=='__total'&&students.some(s=>(op.scoreEntry(exam,s.id,f.subject)??0)>max))throw Error('新满分低于已录成绩，请先核对分数。');const items=JSON.parse(f.ranges) as {id:string;label:string;min:number;max:number}[];if(!Array.isArray(items)||items.some(r=>!r.label||!Number.isFinite(r.min)||!Number.isFinite(r.max)||r.min<0||r.min>r.max||r.max>max))throw Error('分段须有名称且范围在满分内。');return op.patchScoreExam(d,classId,exam.id,{subjectMaxScores:f.subject==='__total'?exam.subjectMaxScores:{...exam.subjectMaxScores,[f.subject]:max},scoreRanges:{...exam.scoreRanges,[f.subject]:items}});}case'item':return checked(op.addScoreKnowledgeItem(d,classId,editor.examId,{title:f.title,subject:f.subject,questionNo:f.questionNo,knowledgePoint:f.knowledgePoint,questionType:f.questionType,maxScore:Number(f.max)},()=>id));case'item-scores':{const item=exam?.knowledgeItems?.find(i=>i.id===f.id);if(!item)throw Error('分析项已不存在。');return students.reduce((cur,s)=>checked(op.setKnowledgeItemScore(cur,classId,editor.examId,item.id,s.id,validValue(f[s.id]??'',item.maxScore))),d);}case'paper':{const items=editor.items??[];if(!items.length||items.some(i=>!i.title.trim()||!Number.isFinite(i.maxScore)||i.maxScore<=0))throw Error('请补全候选名称和有效满分。');return checked(op.confirmScorePaperAnalysis(op.patchScorePaperAnalysis(d,classId,editor.examId,f.id,{items}),classId,editor.examId,f.id));}}},()=>{done();if(editor.kind==='exam'&&!f.id)setExamId(id);});}
 async function toggleFollow(id:string){if(!exam||!guard())return;await apply(d=>op.patchScoreExam(d,classId,exam.id,{followUpStudentIds:exam.followUpStudentIds?.includes(id)?exam.followUpStudentIds.filter(s=>s!==id):[...(exam.followUpStudentIds??[]),id]}));}
 async function remove(){if(!deleteTarget||!exam)return;const target=deleteTarget;await apply(d=>target.kind==='exam'?op.removeScoreExam(d,classId,target.id):op.removeScoreKnowledgeItem(d,classId,exam.id,target.id),()=>{setDeleteTarget(null);setEditor(null);setSelected([]);});}
 const replaceLatest=()=>{leave.current=true;loadLatest();};
 useEffect(()=>{const on=(e:Event)=>{if(!leave.current&&(dirty||pending||busy)){e.preventDefault();setConfirmClose(true);}},unload=(e:BeforeUnloadEvent)=>{if(!leave.current&&(dirty||pending||busy)){e.preventDefault();e.returnValue='';}};window.addEventListener('classroom:before-navigate',on);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('classroom:before-navigate',on);window.removeEventListener('beforeunload',unload);};},[dirty,pending,busy]);
 return {data,classId,students,exams,exam,subjects,shownSubjects,summary,ranges,rows,pagedRows:rows.slice((safePage-1)*10,safePage*10),pages,safePage,setPage,tab,switchTab,query,setQuery,subject,setSubject,group,setGroup,follow,setFollow,range,setRange,sort,setSort,reset,selected,setSelected,editor,setEditor,setField,begin,openExam,openStudent,saveEditor,closeEditor,draftScores,stageScore,saveScores,switchExam,guard,apply,toggleFollow,deleteTarget,setDeleteTarget,remove,dirty,locked,busy,pending,error,setError,message,setMessage,confirmClose,setConfirmClose,discard,sync,readOnly,mobile,conflict,exportDraft,replaceLatest};
}
