'use client';

import { useState } from 'react';
import { CampusIcon } from '@/app/components/campus/primitives';
import { Drawer } from '@/app/components/workbench/ui/Drawer';
import { ThemeBoundary } from '@/app/components/workbench/theme/ThemeBoundary';
import { attendanceStatuses, type useAttendanceDesignController } from './useAttendanceDesignController';
import art from './calendar-p01.png';
import styles from './AttendanceDesign.module.css';

type Controller = ReturnType<typeof useAttendanceDesignController>;
export function AttendanceDesign({ controller: c }: { controller: Controller }) {
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [calendarOpen, setCalendarOpen] = useState(false);
  const [expandedNotes, setExpandedNotes] = useState<string[]>([]);
  const shiftDate = (amount: number) => { const d = new Date(`${c.selectedDate}T12:00:00`); d.setDate(d.getDate() + amount); c.changeDate(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`); };
  const today = () => { const d=new Date(); c.changeDate(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`); };
  const calendar = <div className={styles.calendar} data-att-design="calendar">
    <label className={styles.monthLabel}>月度记录<input type="month" aria-label="选择考勤月份" value={c.month} disabled={c.busy} onChange={e=>{if(e.target.value)c.setMonth(e.target.value);}}/></label>
    <div className={styles.weekdays} aria-hidden="true">{['一','二','三','四','五','六','日'].map(d=><span key={d}>{d}</span>)}</div>
    <div className={styles.days}>{Array.from({length:(new Date(`${c.month}-01T12:00:00`).getDay()+6)%7},(_,i)=><span key={`blank-${i}`}/>)}{c.calendar.map(day=><button key={day.date} type="button" disabled={c.busy} aria-label={`${day.date}，${day.date===c.selectedDate&&(c.busy||c.unsynced)?'本机改动待同步':day.entered?`${day.entered}人已登记，${day.exceptions}人异常`:'无记录'}`} aria-pressed={day.date===c.selectedDate} data-exception={day.exceptions>0||undefined} data-entered={day.entered>0||undefined} onClick={()=>c.changeDate(day.date)}><span>{Number(day.date.slice(-2))}</span><small>{day.date===c.selectedDate&&(c.busy||c.unsynced)?'待同步':day.entered?(day.exceptions?`${day.exceptions}异常`:'已登记'):''}</small></button>)}</div>
    <p className={styles.calendarNote}>无记录不等于正常{(c.busy||c.unsynced)&&'。当前日期含本机待同步改动。'}</p>{c.mobile&&<button type="button" className={styles.textAction} onClick={today}>回到今天</button>}
  </div>;
  const filters = <div className={styles.filters} data-att-design="filters"><label>状态<select aria-label="考勤状态筛选" value={c.statusFilter} onChange={e=>c.setStatusFilter(e.target.value as Controller['statusFilter'])}><option value="全部">全部状态</option>{attendanceStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label>小组<select aria-label="小组筛选" value={c.groupFilter} onChange={e=>c.setGroupFilter(e.target.value)}><option value="全部">全部小组</option>{c.groups.map(g=><option value={g} key={g}>第{g}组</option>)}</select></label>{(c.keyword||c.statusFilter!=='全部'||c.groupFilter!=='全部')&&<button type="button" className={styles.textAction} onClick={()=>{c.setKeyword('');c.setStatusFilter('全部');c.setGroupFilter('全部');}}>重置</button>}</div>;
  return <section className={styles.page} data-att-design="page" data-mobile={c.mobile||undefined}>
    <div className={styles.main}>
      <header className={styles.heading} data-att-design="heading"><h1>考勤与请假</h1><p>{c.activeClass.name}</p></header>
      <div className={styles.dateRow} data-att-design="date"><button type="button" aria-label="前一天" disabled={c.busy} onClick={()=>shiftDate(-1)}>‹</button><label><span className={styles.srOnly}>考勤日期</span><input aria-label="考勤日期" type="date" value={c.selectedDate} disabled={c.busy} onChange={e=>c.changeDate(e.target.value)}/></label><span className={styles.weekday}>{new Date(`${c.selectedDate}T12:00:00`).toLocaleDateString('zh-CN',{weekday:'short'})}</span><button type="button" aria-label="后一天" disabled={c.busy} onClick={()=>shiftDate(1)}>›</button>{!c.mobile&&<button type="button" className={styles.textAction} onClick={today}>今天</button>}{c.mobile&&<button type="button" className={styles.textAction} onClick={()=>setCalendarOpen(true)}>月历</button>}</div>
      <div className={styles.metrics} aria-label="当天考勤概览" data-att-design="metrics">{attendanceStatuses.map(s=><span key={s} data-status={s}><i aria-hidden="true"/>{s}<b>{c.counts[s]}</b></span>)}</div>
      {c.recordsByStudent.size<c.students.length&&<p className={styles.unrecorded}>当天仍有学生无记录，名单暂沿用其当前状态。</p>}
      {c.message&&<div className={styles.message} role={c.messageError?'alert':'status'} data-error={c.messageError||undefined}><span>{c.message}</span><button aria-label="关闭提示" onClick={()=>c.setMessage('')}>×</button></div>}
      <div className={styles.toolbar} data-att-design="toolbar"><label className={styles.search}><CampusIcon name="search"/><span className={styles.srOnly}>搜索学生</span><input aria-label="搜索学生" placeholder="姓名或学号" value={c.keyword} onChange={e=>c.setKeyword(e.target.value)}/></label>{c.mobile?<button type="button" aria-expanded={filtersOpen} className={styles.filterToggle} onClick={()=>setFiltersOpen(!filtersOpen)}>筛选{c.statusFilter!=='全部'||c.groupFilter!=='全部'?' · 已启用':''}</button>:filters}{!c.mobile&&<button type="button" className={styles.allNormal} disabled={c.busy||c.readOnly||!c.students.length} onClick={()=>void c.markAllNormal()}>一键全员正常</button>}</div>
      {c.mobile&&filtersOpen&&filters}
      <section className={styles.roster} aria-label="当日考勤名单" data-att-design="roster"><div className={styles.rosterHead}><h2>当日名单 <small>{c.filteredStudents.length}/{c.students.length}人</small></h2><button type="button" className={styles.textAction} disabled={c.busy||c.readOnly||!c.pageStudents.length} onClick={c.toggleVisible}>{c.allVisibleSelected?'取消本页选择':'全选本页'}</button>{c.mobile&&<button type="button" className={styles.textAction} disabled={c.busy||c.readOnly||!c.students.length} onClick={()=>void c.markAllNormal()}>一键全员正常</button>}</div>
      {c.selectedIds.length>0&&<div className={styles.batch} data-att-design="batch"><strong>已选 {c.selectedIds.length} 人</strong><label>改为<select aria-label="批量考勤状态" disabled={c.busy||c.readOnly} value={c.batchStatus} onChange={e=>c.setBatchStatus(e.target.value as Controller['batchStatus'])}><option>不修改</option>{attendanceStatuses.map(s=><option key={s}>{s}</option>)}</select></label><label className={styles.batchNote}>统一备注<input aria-label="统一备注" placeholder="留空不覆盖原备注" disabled={c.busy||c.readOnly} value={c.batchNote} onChange={e=>c.setBatchNote(e.target.value)}/></label><button type="button" className={styles.primary} disabled={c.busy||c.readOnly} onClick={()=>void c.applyBatch()}>{c.busy?'保存中…':'应用并保存'}</button></div>}
      <div className={styles.tableHead} aria-hidden="true"><span/><span>学生 / 学号</span><span>考勤状态</span><span>当日备注</span><span>操作</span></div>
      <div className={styles.studentList} data-att-design="list">{c.pageStudents.map(student=>{const status=c.statusFor(student,c.recordsByStudent);const note=c.noteDrafts[student.id]??c.recordsByStudent.get(student.id)?.note??'';const expanded=expandedNotes.includes(student.id);return <article key={student.id} data-student-id={student.id} className={styles.student} data-selected={c.selectedIds.includes(student.id)||undefined}><label className={styles.check}><input type="checkbox" aria-label={`选择${student.name}`} checked={c.selectedIds.includes(student.id)} disabled={c.busy||c.readOnly} onChange={()=>c.toggleStudent(student.id)}/></label><div className={styles.identity}><strong>{student.name}</strong><small>{student.studentNo||'未编学号'} · 第{student.group}组</small></div><div className={styles.statuses} role="group" aria-label={`${student.name}考勤状态`}>{attendanceStatuses.map(s=><button type="button" key={s} data-status={s} aria-pressed={s===status} disabled={c.busy||c.readOnly} onClick={()=>void c.setStudentStatus(student.id,s)}>{s}</button>)}</div><div className={styles.note}><label className={styles.srOnly} htmlFor={`note-${student.id}`}>{student.name}当日备注</label>{expanded?<textarea id={`note-${student.id}`} value={note} disabled={c.busy||c.readOnly} onChange={e=>c.setNoteDrafts(v=>({...v,[student.id]:e.target.value}))}/>:<input id={`note-${student.id}`} value={note} placeholder="当日备注（选填）" disabled={c.busy||c.readOnly} onChange={e=>c.setNoteDrafts(v=>({...v,[student.id]:e.target.value}))}/>} {(note.length>24||expanded)&&<button type="button" className={styles.textAction} aria-expanded={expanded} onClick={()=>setExpandedNotes(ids=>expanded?ids.filter(id=>id!==student.id):[...ids,student.id])}>{expanded?'收起备注':'展开全文'}</button>}</div><button type="button" className={styles.saveNote} disabled={c.busy||c.readOnly} onClick={()=>void c.saveStudentNote(student.id)}>保存</button></article>;})}
      {!c.filteredStudents.length&&<div className={styles.empty}><h3>{c.students.length?'没有匹配的学生':'班级里还没有学生'}</h3><p>{c.students.length?'试试其他姓名、学号或筛选条件。':'添加学生后，就可以在这里登记每天的考勤。'}</p>{c.students.length>0&&<button type="button" className={styles.textAction} onClick={()=>{c.setKeyword('');c.setStatusFilter('全部');c.setGroupFilter('全部');}}>清除搜索和筛选</button>}</div>}</div>
      <nav className={styles.pagination} aria-label="考勤名单分页"><span>共 {c.filteredStudents.length} 人 · 第 {c.safeListPage}/{c.listPageCount} 页</span>{c.listPageCount>1&&<div><button type="button" disabled={c.safeListPage===1||c.busy} onClick={()=>c.setListPage(p=>Math.max(1,p-1))}>上一页</button><button type="button" disabled={c.safeListPage===c.listPageCount||c.busy} onClick={()=>c.setListPage(p=>Math.min(c.listPageCount,p+1))}>下一页</button></div>}</nav></section>
    </div>
    {!c.mobile&&<aside className={styles.aside}>{calendar}<img className={styles.art} src={typeof art==='string'?art:art.src} alt="" width="1536" height="1024"/></aside>}
    <ThemeBoundary><Drawer open={calendarOpen&&c.mobile} title="考勤月历" onRequestClose={()=>setCalendarOpen(false)}>{calendar}</Drawer></ThemeBoundary>
  </section>;
}
