import {useState} from 'react';
import {ThemeBoundary} from '@/app/components/workbench/theme/ThemeBoundary';
import {Dialog} from '@/app/components/workbench/ui/Dialog';
import {StudentPicker} from '@/app/components/workbench/ui/StudentPicker';
import {CampusIcon} from '@/app/components/campus/primitives';
import {recordFields,recordStatus,recordTypes,recordChannels,type useRecordsDesignController} from './useRecordsDesignController';
import type {CommunicationRecordDraft} from '@/app/w/[token]/features/records/operations';
import type {NotificationDraft} from '@/lib/classroom';
import art from './letter-p01.png';
import s from './RecordsDesign.module.css';
type Controller=ReturnType<typeof useRecordsDesignController>;
export function RecordsDesign({controller:c}:{controller:Controller}){
 const [filtersOpen,setFiltersOpen]=useState(false),[picker,setPicker]=useState<'student'|'recipients'|null>(null),[noticeDetailId,setNoticeDetailId]=useState(''),[moreId,setMoreId]=useState(''),[replace,setReplace]=useState(false);
 const e=c.editor,detail=c.detail,noticeDetail=c.notices.find(n=>n.id===noticeDetailId),count=(status:string)=>c.records.filter(r=>recordStatus(r)===status).length;
 const recipients=(n:Pick<NotificationDraft,'recipientStudentIds'>)=>!n.recipientStudentIds?.length?'全班家长':n.recipientStudentIds.map(id=>c.students.find(st=>st.id===id)?.name??'已移除学生').join('、')+'家长';
 const setRecord=<K extends keyof CommunicationRecordDraft>(key:K,value:CommunicationRecordDraft[K])=>{if(e?.kind==='record')c.setEditor({...e,value:{...e.value,[key]:value}});};
 const recovery=<>{c.error&&<p role="alert" className={s.error}>{c.error}</p>}{c.pending&&<div className={s.recovery}><p>改动已在本机待同步。重试不会重复提交同一条记录。</p><button disabled={c.busy} onClick={()=>void c.sync()}>重试同步</button>{c.conflict&&<><button onClick={c.exportDraft}>导出草稿</button><button onClick={()=>setReplace(true)}>载入最新数据</button></>}</div>}</>;
 const filters=<div className={s.filters}><label>类型<select aria-label="沟通类型筛选" value={c.type} onChange={ev=>c.setType(ev.target.value)}>{['全部类型',...new Set(c.records.map(r=>r.type))].map(v=><option key={v}>{v}</option>)}</select></label><button onClick={c.reset}>重置筛选</button></div>;
 const notifications=<aside className={s.notifications} aria-label="通知草稿与回执"><header><h2>通知草稿与回执</h2><button className={s.primary} disabled={c.readOnly||c.locked} onClick={()=>c.openNotice()}>新建草稿</button></header><p className={s.noticeHint}>复制后由老师自行发送，系统不自动外发。</p>{c.noticeRows.map(n=><article className={s.notice} key={n.id} data-notice-id={n.id}><div className={s.noticeMeta}><span className={s.badge} data-status={n.status}>{n.status}</span><time>{n.date}</time></div><h3>{n.title}</h3><p className={s.recipientLine}>{n.channel} · {recipients(n)}</p><p className={s.noticeContent}>{n.content}</p>{n.receiptNote&&<p className={s.receipt}>回执：{n.receiptNote}</p>}<button className={s.textLink} onClick={()=>setNoticeDetailId(n.id)}>查看完整通知</button><footer><button className={s.primary} disabled={c.locked} onClick={()=>void c.copyNotice(n)}>复制通知</button><button disabled={c.readOnly||c.locked} onClick={()=>c.openReceipt(n)}>记录回执</button><button aria-expanded={moreId===n.id} disabled={c.readOnly||c.locked} onClick={()=>setMoreId(moreId===n.id?'':n.id)}>更多</button></footer>{moreId===n.id&&<div className={s.more}><button onClick={()=>{c.openNotice(n);setMoreId('');}}>编辑草稿</button><button className={s.danger} onClick={()=>{c.setDeleteTarget({kind:'notice',id:n.id,title:n.title});setMoreId('');}}>删除草稿</button></div>}</article>)}{!c.notices.length&&<div className={s.empty}><h3>暂无通知草稿</h3><p>可先整理需要家长配合的事项。</p></div>}{c.noticePages>1&&<nav className={s.pagination} aria-label="通知分页"><button disabled={c.safeNoticePage===1} onClick={()=>c.setNoticePage(p=>p-1)}>上一页</button><span>{c.safeNoticePage}/{c.noticePages}</span><button disabled={c.safeNoticePage===c.noticePages} onClick={()=>c.setNoticePage(p=>p+1)}>下一页</button></nav>}</aside>;
 return <main className={s.page} data-records-design="page" data-mobile={c.mobile||undefined}>
  <header className={s.heading}><div><h1>家校沟通</h1><p>{c.mobile?c.activeClass?.name:'先看跟进约定，再回顾沟通事实。'}</p><span>{c.records.length}条沟通记录 · {count('待跟进')}条待跟进</span></div>{!c.mobile&&<button className={s.primary} disabled={c.readOnly||c.locked||!c.students.length} onClick={()=>c.openRecord()}><CampusIcon name="plus"/>新增沟通记录</button>}<img src={typeof art==='string'?art:art.src} alt="" width="1536" height="1024"/></header>
  {c.mobile&&<nav className={s.mobileTabs} aria-label="沟通工作区"><button aria-pressed={c.tab==='records'} onClick={()=>c.setTab('records')}>沟通记录 {c.records.length}</button><button aria-pressed={c.tab==='notices'} onClick={()=>c.setTab('notices')}>通知草稿 {c.notices.length}</button></nav>}
  {c.message&&<div className={s.message} role="status">{c.message}<button onClick={()=>c.setMessage('')}>关闭提示</button></div>}{!e&&recovery}
  <div className={s.layout}>{(!c.mobile||c.tab==='records')&&<section className={s.ledger} aria-label="沟通记录清单"><div className={s.toolbar}><label className={s.search}><CampusIcon name="search"/><input aria-label="搜索沟通记录" placeholder="搜索学生或沟通内容" value={c.query} onChange={ev=>c.setQuery(ev.target.value)}/></label>{c.mobile?<button aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(!filtersOpen)}>筛选</button>:filters}</div>{c.mobile&&filtersOpen&&filters}<nav className={s.statusTabs} aria-label="沟通状态筛选">{['全部','待跟进','已跟进','已归档'].map(v=><button key={v} aria-pressed={c.status===v} onClick={()=>c.setStatus(v)}>{v} <span>{v==='全部'?c.records.length:count(v)}</span></button>)}</nav>{c.mobile&&<div className={s.mobileCommand}><span>{c.filtered.length}条记录</span><button disabled={c.readOnly||c.locked||!c.students.length} onClick={()=>c.openRecord()}><CampusIcon name="plus"/>新增记录</button></div>}
   {['待跟进','已跟进','已归档'].map(group=>{const rows=c.rows.filter(r=>recordStatus(r)===group);return rows.length?<section key={group} className={s.group}><h2>{group} <small>本页{rows.length}条</small></h2>{rows.map(r=><article key={r.id} className={s.row} data-record-id={r.id}><time className={s.recordDate}>{r.date}</time><div className={s.recordBody}><header><h3>{r.student}</h3><span className={s.badge} data-status={recordStatus(r)}>{recordStatus(r)}</span></header><p className={s.recordMeta}>{c.mobile&&<span>{r.date} · </span>}{r.type} · {r.channel??'面谈'}</p><p className={s.fact}>{recordFields(r.content).content}</p>{r.parentFeedback&&<p className={s.feedback}>反馈：{r.parentFeedback}</p>}<div className={s.nextRow}>{r.followUp&&<p className={s.followUp}>下一步：{r.followUp}</p>}<button onClick={()=>c.setDetailId(r.id)} aria-label={`查看${r.student}的沟通详情`}>{c.mobile?'详情':'查看详情'}<CampusIcon name="chevron"/></button></div></div></article>)}</section>:null;})}
   {!c.rows.length&&<div className={s.empty}><h2>{c.records.length?'没有匹配的沟通记录':c.students.length?'还没有沟通记录':'先建立学生名单'}</h2><p>{c.records.length?'换一个关键词或筛选条件试试。':'记录沟通事实、家长反馈与后续约定。'}</p>{c.records.length>0&&<button onClick={c.reset}>清除搜索和筛选</button>}</div>}
   <nav className={s.pagination} aria-label="沟通记录分页"><span>共{c.filtered.length}条</span>{c.pages>1&&<><button disabled={c.safePage===1} onClick={()=>c.setPage(p=>p-1)}>上一页</button><span>{c.safePage}/{c.pages}</span><button disabled={c.safePage===c.pages} onClick={()=>c.setPage(p=>p+1)}>下一页</button></>}</nav>
  </section>}{(!c.mobile||c.tab==='notices')&&notifications}</div>
  <ThemeBoundary>
   <Dialog open={!!detail} title={detail?`${detail.student} · ${detail.type}`:'沟通详情'} onRequestClose={()=>c.setDetailId('')} footer={detail&&<><button disabled={c.readOnly||c.locked} onClick={()=>c.openRecord(detail)}>编辑记录</button><button onClick={()=>void c.copyRecord(detail)}>复制记录</button><button className={s.danger} disabled={c.readOnly||c.locked} onClick={()=>c.setDeleteTarget({kind:'record',id:detail.id,title:`${detail.student}的沟通记录`})}>删除记录</button></>}>{detail&&<div className={s.details}><p>{detail.date} · {detail.channel??'面谈'}</p><label>状态<select aria-label="修改沟通状态" disabled={c.readOnly||c.locked} value={recordStatus(detail)} onChange={ev=>void c.changeStatus(detail,ev.target.value as typeof detail.status)}>{['待跟进','已跟进','已归档'].map(v=><option key={v}>{v}</option>)}</select></label><h3>沟通目的</h3><p>{recordFields(detail.content).purpose||'未填写'}</p><h3>家庭与在校情况</h3><p>{recordFields(detail.content).home||'未填写'}</p><h3>沟通事实</h3><p>{recordFields(detail.content).content}</p><h3>家长反馈</h3><p>{detail.parentFeedback||'暂无反馈'}</p><h3>下一步跟进</h3><p>{detail.followUp||'暂无跟进安排'}</p>{!e&&recovery}</div>}</Dialog>
   <Dialog open={!!noticeDetail} title={noticeDetail?.title??'通知内容'} onRequestClose={()=>setNoticeDetailId('')} footer={noticeDetail&&<button disabled={c.locked} onClick={()=>void c.copyNotice(noticeDetail)}>复制通知</button>}>{noticeDetail&&<div className={s.details}><p>{noticeDetail.date} · {noticeDetail.channel} · {noticeDetail.status}</p><h3>通知对象</h3><p>{recipients(noticeDetail)}</p><h3>通知内容</h3><p>{noticeDetail.content}</p><h3>回执记录</h3><p>{noticeDetail.receiptNote||'尚未记录回执'}</p><p>复制后由老师自行发送，系统不自动外发。</p>{recovery}</div>}</Dialog>
   {e&&<Dialog open title={e.kind==='record'?(e.value.id?'编辑沟通记录':'新增沟通记录'):e.kind==='notice'?(e.value.id?'编辑通知草稿':'新建通知草稿'):'记录回执'} busy={c.busy} dirty={c.dirty} onRequestClose={c.requestClose} footer={<><button disabled={c.busy} onClick={c.requestClose}>取消</button><button className={s.primary} disabled={c.readOnly||c.busy} onClick={()=>void c.saveEditor()}>{c.busy?'保存中…':c.pending?'重试同步':e.kind==='record'?'保存记录':e.kind==='notice'?'保存草稿':'保存回执'}</button></>}>
    <fieldset className={s.editor} disabled={c.readOnly||c.locked}>
     {e.kind==='record'&&<><label>学生（必选）<button onClick={()=>setPicker('student')}>{c.students.find(st=>st.id===e.value.studentId)?.name??'搜索姓名或学号选择学生'}</button></label><label>沟通时间<input aria-label="沟通时间" value={e.value.date} onChange={ev=>setRecord('date',ev.target.value)} placeholder="日期或原有时间描述"/></label><div className={s.formGrid}><label>类型<input aria-label="编辑沟通类型" list="record-type-options" value={e.value.type} onChange={ev=>setRecord('type',ev.target.value)}/><datalist id="record-type-options">{recordTypes.map(v=><option key={v}>{v}</option>)}</datalist></label><label>方式<input aria-label="编辑沟通方式" list="record-channel-options" value={e.value.channel} onChange={ev=>setRecord('channel',ev.target.value)}/><datalist id="record-channel-options">{recordChannels.map(v=><option key={v}>{v}</option>)}</datalist></label></div><label>沟通目的<input value={e.value.purpose} onChange={ev=>setRecord('purpose',ev.target.value)}/></label>{([['home','家庭与在校情况'],['content','沟通内容'],['parentFeedback','家长反馈'],['followUp','下一步跟进']] as const).map(([key,label])=><label key={key}>{label}{key==='content'?'（必填）':'（选填）'}<textarea aria-label={label} value={e.value[key]} onChange={ev=>setRecord(key,ev.target.value)}/></label>)}</>}
     {e.kind==='notice'&&<><label>通知对象<button onClick={()=>setPicker('recipients')}>{recipients(e.value)}</button></label><label>沟通渠道<select aria-label="通知渠道" value={e.value.channel} onChange={ev=>c.setEditor({...e,value:{...e.value,channel:ev.target.value as NotificationDraft['channel']}})}>{['班级群','私聊','电话提醒'].map(v=><option key={v}>{v}</option>)}</select></label><label>标题（必填）<input aria-label="通知标题" value={e.value.title} onChange={ev=>c.setEditor({...e,value:{...e.value,title:ev.target.value}})}/></label><label>通知内容（必填）<textarea aria-label="通知内容" value={e.value.content} onChange={ev=>c.setEditor({...e,value:{...e.value,content:ev.target.value}})}/></label><p>只保存草稿，不向家长发送信息。</p></>}
     {e.kind==='receipt'&&<><p>仅记录老师已收到的反馈，不会向家长发送信息。</p><label>回执内容<textarea aria-label="回执内容" value={e.note} onChange={ev=>c.setEditor({...e,note:ev.target.value})}/></label><p>留空保存将按已有规则记录“已确认知晓”。</p></>}
    </fieldset>{recovery}
   </Dialog>}
   {picker&&e&&<StudentPicker open title={picker==='student'?'选择沟通学生':'选择通知对象'} description={picker==='student'?'按姓名或学号查找学生。':'未选个人表示全班家长；可搜索并选择多人。'} items={c.students} selectionMode={picker==='student'?'single':'multiple'} allowEmptySelection={picker==='recipients'} clearLabel="改为全班家长" selectedIds={e.kind==='record'?[e.value.studentId].filter(Boolean):e.kind==='notice'?e.value.recipientStudentIds:[]} confirmLabel="使用所选对象" onRequestClose={()=>setPicker(null)} onConfirm={ids=>{if(e.kind==='record')setRecord('studentId',ids[0]??'');if(e.kind==='notice')c.setEditor({...e,value:{...e.value,recipientStudentIds:ids}});setPicker(null);}}/>}
   <Dialog open={c.confirmClose} title={c.pending?'还有待同步改动':'放弃未保存改动？'} onRequestClose={()=>c.setConfirmClose(false)} footer={<><button onClick={()=>c.setConfirmClose(false)}>继续处理</button>{!c.pending&&<button onClick={c.discard}>放弃改动</button>}</>}><p>{c.pending?'本机改动需要先同步；关闭不会撤销它。':'放弃后将不保留本次输入。'}</p></Dialog>
   <Dialog open={!!c.deleteTarget} title="确认删除" onRequestClose={()=>c.setDeleteTarget(null)} footer={<><button onClick={()=>c.setDeleteTarget(null)}>取消删除</button><button className={s.danger} disabled={c.locked||c.readOnly} onClick={()=>void c.remove()}>确认删除</button></>}><p>{c.deleteTarget?.title}将从当前班级移除，且无法恢复。</p></Dialog>
   <Dialog open={replace} title="载入最新数据？" onRequestClose={()=>setReplace(false)} footer={<><button onClick={()=>setReplace(false)}>保留本机草稿</button><button onClick={c.replaceLatest}>确认载入最新</button></>}><p>载入会替换本机待同步改动，请先导出需要保留的草稿。</p></Dialog>
  </ThemeBoundary>
 </main>;
}
