'use client';
import { useRef,useState } from 'react';
import type { ClassroomData } from '@/lib/classroom';
import { makeId } from '@/lib/classroom';
import { assertDictation,contextKey,emptyDictation,newTask,statistics,taskState,today,wrongWords,type DictationData,type DictationTask,type FamilyChild,type LearningContext,type Participant } from '@/lib/dictation';
import { Button,CampusIcon,EmptyState,PageHeader,Pager } from '@/app/components/campus/primitives';
import { PersonFilter } from './PersonFilter';
import { WordLibrary } from './WordLibrary';
import { TaskEditor } from './TaskEditor';
import { Grading } from './Grading';
import './dictation.css';
export type CommitWorkspace = (updater:(data:ClassroomData)=>ClassroomData)=>Promise<boolean>;
function confirmAction(message:string,title='确认操作',confirmLabel='确认'){return new Promise<boolean>(onResolve=>window.dispatchEvent(new CustomEvent('classroom:confirm',{detail:{message,title,confirmLabel,onResolve}})));}
import { canLeaveDictation } from './navigation';
export default function Dictation({data,token,readOnly,commit,scene,onSceneChange}: {data:ClassroomData;token:string;readOnly:boolean;commit:CommitWorkspace;scene:'class'|'family';onSceneChange:(scene:'class'|'family')=>void}) {
 const d=data.dictation??emptyDictation();
 const [childId,setChildId]=useState(d.children.find(c=>!c.archived)?.id??''),[view,setView]=useState('tasks'),[taskId,setTaskId]=useState(''),[editing,setEditing]=useState<DictationTask|undefined>(),[query,setQuery]=useState(''),[subject,setSubject]=useState(''),[person,setPerson]=useState(''),[date,setDate]=useState(''),[page,setPage]=useState(1),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[childForm,setChildForm]=useState<FamilyChild|null>(null);
 const pendingAction=useRef<{key:string;task:DictationTask}|null>(null);
 const classId=data.activeClassId??data.rosterClasses?.[0]?.id??'';
 const context:LearningContext=scene==='class'?{kind:'class',classId}:{kind:'family',childId};
 const child=scene==='family'?d.children.find(c=>c.id===childId):undefined;const classroom=data.rosterClasses?.find(c=>c.id===classId);
 const participants:Participant[]=scene==='class'?(classroom?.students??[]).map(s=>({id:s.id,name:s.name,number:s.studentNo??''})):child?[{id:child.id,name:child.name,number:''}]:[];
 const scoped=d.tasks.filter(t=>contextKey(t.context)===contextKey(context));
 const selected=scoped.find(t=>t.id===taskId);
 const filtered=scoped.filter(t=>(view==='wrong'||!query||t.title.toLowerCase().includes(query.toLowerCase()))&&(!subject||t.subject===subject)&&(!date||t.date===date));
 const list=filtered.filter(t=>view==='history'||!t.archived).toSorted((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));
 const cutoff=new Date();cutoff.setDate(cutoff.getDate()-29);const from=cutoff.toLocaleDateString('sv-SE');
 const recent=filtered.filter(t=>t.date>=from&&t.date<=today());
 const historyPeople=[...new Map([...participants,...scoped.flatMap(t=>t.participants)].map(p=>[p.id,p])).values()];
 const chosenPerson=person||undefined;
 const stats=statistics(recent,chosenPerson),initialStats=statistics(recent.filter(t=>!t.sourceId),chosenPerson),reviewStats=statistics(recent.filter(t=>t.sourceId),chosenPerson);
 const wrong=wrongWords(filtered,chosenPerson).filter(w=>!query||w.word.text.toLowerCase().includes(query.toLowerCase())||w.participant.name.includes(query));
 function navigate(next:string){if(!canLeaveDictation())return;setView(next);setTaskId('');setEditing(undefined);setPage(1);setQuery('');setDate('');setMessage('');}
 async function change(updater:(x:DictationData)=>DictationData){if(readOnly){setMessage('当前为只读模式');return false;}setBusy(true);try{const ok=await commit(current=>{const next={...current,dictation:updater(current.dictation??emptyDictation())};assertDictation(next.dictation,next,current);return next;});setMessage(ok?'服务器已确认保存':'保存未完成，草稿已保留。请重试或核对版本冲突。');return ok;}catch(e){setMessage(e instanceof Error?e.message:'保存失败');return false;}finally{setBusy(false);}}
 async function saveTask(t:DictationTask){const ok=await change(x=>({...x,tasks:x.tasks.some(v=>v.id===t.id)?x.tasks.map(v=>v.id===t.id?t:v):[...x.tasks,t]}));if(ok){setTaskId(t.id);setView('grading');setEditing(undefined);}return ok;}
 async function repeat(t:DictationTask,reviewPerson?:Participant,nextLesson=false){if(busy||readOnly||child?.archived)return;let words=t.words,lesson=t.lesson,title=`${t.title} · 复听`;if(reviewPerson){words=t.words.filter((_,i)=>t.results[reviewPerson.id]?.[1].includes(i));title=`${reviewPerson.name} · 错词复习`;}if(nextLesson){const book=d.books.find(b=>b.id===t.bookId);const lessons=[...new Set(book?.entries.map(w=>w.lesson)??[])];lesson=lessons[lessons.indexOf(t.lesson??'')+1];if(!book||!lesson){setMessage('没有下一课，请在词库补充内容');return;}words=book.entries.filter(w=>w.lesson===lesson);title=`${book.title} · ${lesson}`;}
 if(!words.length){setMessage('没有需要复习的错词');return;}const existing=reviewPerson&&d.tasks.find(v=>v.sourceId===t.id&&v.date===today()&&v.participants.length===1&&v.participants[0].id===reviewPerson.id);if(existing){setTaskId(existing.id);setView('grading');setMessage('已打开本日已安排的复习');return;}
 const currentIds=new Set(participants.map(p=>p.id));const people=(reviewPerson?[reviewPerson]:t.participants).filter(p=>currentIds.has(p.id));if(!people.length){setMessage('原参与者已不在当前名册，历史记录仍可查看');return;}
 try{const key=`${t.id}:${reviewPerson?.id??''}:${nextLesson}`;const task=(pendingAction.current?.key===key?pendingAction.current.task:undefined)??newTask({...t,participants:people,words,lesson,title,date:today(),sourceId:nextLesson?undefined:t.id,archived:false});pendingAction.current={key,task};if(await saveTask(task))pendingAction.current=null;}catch(e){setMessage(e instanceof Error?e.message:'创建失败');}}
 async function saveChild(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!childForm||busy)return;const f=new FormData(e.currentTarget);const c={...childForm,name:String(f.get('name')).trim(),grade:String(f.get('grade')).trim()};if(await change(x=>({...x,children:x.children.some(v=>v.id===c.id)?x.children.map(v=>v.id===c.id?c:v):[...x.children,c]}))){setChildId(c.id);setChildForm(null);}}
 return <section className="dictation-workspace" data-view={view}><PageHeader title="听写与复习" actions={view!=='grading'&&view!=='create'&&<Button intent="primary" disabled={readOnly||busy||!participants.length||Boolean(child?.archived)} onClick={()=>navigate('create')}><CampusIcon name="plus"/>新建听写</Button>}/>
 <div className="dictation-context"><div className="campus-tabs" aria-label="学习场景">{(['class','family'] as const).map(s=><button key={s} aria-pressed={scene===s} onClick={()=>{if(!canLeaveDictation())return;onSceneChange(s);setView('tasks');setTaskId('');setPerson('');setPage(1);}}>{s==='class'?'班级教学':'家庭学习'}</button>)}</div>{scene==='class'?<span>{classroom?.name??'当前班级'} · {participants.length}人</span>:<label>当前孩子<select value={childId} onChange={e=>{if(!canLeaveDictation())return;setChildId(e.target.value);setTaskId('');setView('tasks');setPerson('');}}><option value="">选择孩子</option>{d.children.map(c=><option key={c.id} value={c.id}>{c.name}{c.archived?'（已归档）':''}</option>)}</select></label>}</div>
 {readOnly&&<p className="campus-inline-alert">只读模式：可以浏览与打印；创建、修改和批改不可用。</p>}
 <nav className="campus-tabs" aria-label="听写子页面">{[['tasks','任务'],['books','词库'],['wrong','错词本'],['history','记录与统计'],...(scene==='family'?[['children','孩子档案']]:[])].map(([id,label])=><button key={id} aria-pressed={view===id} onClick={()=>navigate(id)}>{label}</button>)}</nav>
 {message&&<p role="status" className="dictation-feedback">{message}</p>}
 {view==='create'&&<TaskEditor data={data} context={context} participants={participants} initial={editing} onSave={saveTask} onCancel={()=>navigate('tasks')} readOnly={readOnly}/>}
 {view==='grading'&&selected&&<Grading key={selected.id} task={selected} token={token} readOnly={readOnly||Boolean(child?.archived)} onBack={()=>navigate('tasks')} onSave={(id,result)=>change(x=>({...x,tasks:x.tasks.map(t=>t.id===selected.id?{...t,results:{...t.results,[id]:result}}:t)}))} onReview={p=>repeat(selected,p)}/>}
 {view==='books'&&<WordLibrary books={d.books} readOnly={readOnly} save={b=>change(x=>({...x,books:x.books.some(v=>v.id===b.id)?x.books.map(v=>v.id===b.id?b:v):[...x.books,b]}))} remove={async id=>{if(await confirmAction('删除词库不影响已建立任务的材料快照。','删除词库','确认删除'))await change(x=>({...x,books:x.books.filter(b=>b.id!==id)}));}}/>}
 {view==='children'&&<><p>孩子档案仅属于当前账户的家庭学习，不加入任何班级名册。</p>{childForm?<form className="dictation-form" onSubmit={saveChild}><label>孩子姓名<input name="name" required maxLength={80} defaultValue={childForm.name}/></label><label>年级（可选）<input name="grade" maxLength={80} defaultValue={childForm.grade}/></label><div className="campus-actions"><Button disabled={busy} onClick={()=>setChildForm(null)}>取消</Button><Button type="submit" intent="primary" disabled={busy||readOnly}>保存孩子档案</Button></div></form>:<Button intent="primary" disabled={readOnly} onClick={()=>setChildForm({id:makeId('child'),name:'',grade:''})}>新增孩子</Button>}{d.children.map(c=><article className="dictation-record" key={c.id}><div><h3>{c.name}</h3><p>{c.grade} {c.archived?'已归档':'使用中'}</p></div><Button intent="text" disabled={readOnly} onClick={()=>setChildForm(c)}>编辑</Button><Button intent="text" disabled={readOnly||busy} onClick={async()=>{if(await confirmAction(c.archived?'恢复此孩子的学习入口？':'归档后保留历史记录，暂停新增任务。','孩子档案',c.archived?'恢复':'归档'))await change(x=>({...x,children:x.children.map(v=>v.id===c.id?{...v,archived:!v.archived}:v)}));}}>{c.archived?'恢复':'归档'}</Button></article>)}</>}
 {['tasks','history','wrong'].includes(view)&&<><div className="campus-toolbar"><label>搜索{view==='wrong'?'词语或姓名':'任务'}<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label>学科<select value={subject} onChange={e=>{setSubject(e.target.value);setPage(1);}}><option value="">全部学科</option>{[...new Set(scoped.map(t=>t.subject))].map(s=><option key={s}>{s}</option>)}</select></label>{view!=='wrong'&&<label>日期<input type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(1);}}/></label>}<Button intent="text" onClick={()=>{setQuery('');setSubject('');setDate('');setPerson('');setPage(1);}}>重置</Button></div>
 {scene==='class'&&view!=='tasks'&&<PersonFilter people={historyPeople} value={person} onChange={id=>{setPerson(id);setPage(1);}}/>}
 {view==='history'&&<><h3>近30天 · {from} 至 {today()}</h3><div className="campus-summary"><span><b>{stats.graded}</b>已批改人次</span><span><b>{stats.rate===null?'无数据':`${(stats.rate*100).toFixed(1)}%`}</b>错误率</span><span>{stats.wrong} / {stats.words} 错误词次</span><span>{stats.leave}请假 · {stats.absent}未参加 · {stats.pending}待批改</span></div><p>首次听写 {initialStats.wrong}/{initialStats.words} 错误词次；复习 {reviewStats.wrong}/{reviewStats.words}。仅统计已确认且实际参与的结果，按词次加权。</p></>}
 {view==='wrong'?<>{!wrong.length?<EmptyState>暂无匹配的已确认错词。未批改不会视为全对。</EmptyState>:<div className="dictation-table-scroll"><table><thead><tr><th>学生 / 孩子</th><th>词语</th><th>错误次数</th><th>最近练习</th><th>来源与复习</th></tr></thead><tbody>{wrong.slice((page-1)*20,page*20).map((w,i)=><tr key={`${w.participant.id}-${w.word.id}-${i}`}><td>{w.participant.name}</td><td>{w.word.text}<small>{w.word.meaning}</small></td><td>{w.count}</td><td>{w.last}</td><td><Button intent="text" onClick={()=>{setTaskId(w.sourceIds.at(-1)!);setView('grading');}}>查看来源</Button><Button disabled={readOnly||busy} onClick={()=>void repeat(scoped.find(t=>t.id===w.sourceIds.at(-1))!,w.participant)}>安排复习</Button></td></tr>)}</tbody></table></div>}<Pager page={page} count={wrong.length} onPage={setPage}/><p>错词历史保留；复习答对不会抹去之前的错误记录。</p></>:<>{!list.length?<EmptyState>{scene==='family'&&!child?'请先在孩子档案中添加或选择孩子。':'暂无匹配任务，可新建听写或从词库选择材料。'}</EmptyState>:list.slice((page-1)*20,page*20).map(t=><article className="dictation-record" key={t.id}><div><h3>{t.title}</h3><p>{t.date} · {t.subject} · {t.words.length}词 · {t.participants.length}人 {t.sourceId?'· 复习轮次':''} {t.archived?'· 已归档':''}</p><span className="dictation-badge">{taskState(t)}</span>{view==='history'&&<p>{statistics([t],chosenPerson).graded}已批改 · {statistics([t],chosenPerson).pending}待批改 · {statistics([t],chosenPerson).wrong}错误词次；逐生明细见查看与批改。</p>}</div><div className="dictation-record-actions"><Button onClick={()=>{setTaskId(t.id);setView('grading');}}>查看 / 批改</Button>{!Object.keys(t.results).length&&<Button intent="text" disabled={readOnly||busy} onClick={()=>{setEditing(t);setView('create');}}>编辑</Button>}<Button intent="text" disabled={readOnly||busy} onClick={()=>void repeat(t)}>复听</Button>{t.bookId&&t.lesson&&<Button intent="text" disabled={readOnly||busy} onClick={()=>void repeat(t,undefined,true)}>下一课 / 组</Button>}<Button intent="text" disabled={readOnly||busy} onClick={()=>void change(x=>({...x,tasks:x.tasks.map(v=>v.id===t.id?{...v,archived:!v.archived}:v)}))}>{t.archived?'恢复':'归档'}</Button><Button intent="danger" disabled={readOnly||busy} onClick={async()=>{if(await confirmAction('此任务和批改记录会永久删除。需要长期留存时请先导出完整备份。','删除听写','确认删除'))await change(x=>({...x,tasks:x.tasks.filter(v=>v.id!==t.id)}));}}>删除</Button></div></article>)}<Pager page={page} count={list.length} onPage={setPage}/></>}
 </>}
 <small className="dictation-capacity">工作区占用 {(new Blob([JSON.stringify(data)]).size/1024/1024).toFixed(2)} / 5 MB。归档保留记录且不减小备份；接近上限时先导出完整备份再整理历史。</small>
 </section>;
}
