'use client';
import { useEffect,useRef,useState } from 'react';
import { type DictationResult,type DictationTask,type Participant } from '@/lib/dictation';
import { Button,Pager,ThemeArtwork } from '@/app/components/campus/primitives';
export function Grading({task,token,readOnly,onSave,onBack,onReview}: {task:DictationTask;token:string;readOnly:boolean;onSave:(id:string,result:DictationResult)=>Promise<boolean>;onBack:()=>void;onReview:(p:Participant)=>Promise<void>}) {
 const [studentId,setStudentId]=useState(task.participants.find(p=>!task.results[p.id])?.id??task.participants[0].id),[query,setQuery]=useState(''),[pendingOnly,setPendingOnly]=useState(false),[page,setPage]=useState(1),[wrong,setWrong]=useState<number[]>([]),[state,setState]=useState<DictationResult[0]>('graded'),[confirmed,setConfirmed]=useState(false),[note,setNote]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[showRoster,setShowRoster]=useState(false);
 const saved=task.results[studentId],student=task.participants.find(p=>p.id===studentId)!;
 const storageKey=`classroom-dictation-draft:${token}:${task.id}:${studentId}`;
 const resultRef=useRef<DictationResult|null>(null);
 const rows=task.participants.filter(p=>(!pendingOnly||!task.results[p.id])&&`${p.name} ${p.number}`.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{
   const r=task.results[studentId];setWrong(r?.[1]??[]);setState(r?.[0]??'graded');setConfirmed(false);setNote(r?.[3]??'');setDirty(false);resultRef.current=null;setMessage('');
   if(readOnly)return;
   try{const raw=localStorage.getItem(storageKey);if(raw){const d=JSON.parse(raw);if(Array.isArray(d.wrong)&&d.wrong.every((n:unknown)=>Number.isInteger(n)&&Number(n)>=0&&Number(n)<task.words.length)&&['graded','leave','absent'].includes(d.state)&&typeof d.note==='string'){setWrong(d.wrong);setState(d.state);setNote(d.note);setDirty(true);setMessage('已恢复本机批改草稿，请核对并确认。');}}}catch{setMessage('本机草稿不可读取，请核对纸面记录。');}
 // Selection changes reload only that participant; server acknowledgements must not erase an in-flight draft.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[studentId,storageKey,readOnly]);
 useEffect(()=>{if(!dirty||readOnly)return;try{localStorage.setItem(storageKey,JSON.stringify({wrong,state,note}));}catch{setMessage('本机草稿存储不可用，请保持本页打开并重试保存。');}},[wrong,state,note,dirty,storageKey,readOnly]);
 useEffect(()=>{if(!dirty&&!busy)return;const guard=(e:Event)=>{e.preventDefault();setMessage('当前批改尚未保存，请先保存或放弃本次修改。');};const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('classroom:before-navigate',guard);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('classroom:before-navigate',guard);window.removeEventListener('beforeunload',unload);};},[dirty,busy]);
 function changeStudent(id:string){if(dirty||busy){setMessage('请先保存当前批改，或点击“放弃修改”。');return;}setStudentId(id);setShowRoster(false);}
 function discard(){setWrong(saved?.[1]??[]);setState(saved?.[0]??'graded');setNote(saved?.[3]??'');setConfirmed(false);setDirty(false);resultRef.current=null;try{localStorage.removeItem(storageKey);}catch{}setMessage('已放弃本次未确认修改');}
 async function save(){if(readOnly||busy||!confirmed)return;setBusy(true);setMessage('正在保存…');const r=resultRef.current??[state,state==='graded'?wrong:[],new Date().toISOString(),note] as DictationResult;resultRef.current=r;try{if(!await onSave(studentId,r)){setDirty(true);setMessage('保存失败，仍停留在当前学生。请重试；若版本冲突，请先导出草稿并核对最新数据。');return;}setDirty(false);setConfirmed(false);resultRef.current=null;try{localStorage.removeItem(storageKey);}catch{}setMessage('服务器已确认保存');const next=task.participants.find(p=>p.id!==studentId&&!task.results[p.id]);if(next)setStudentId(next.id);}catch{setDirty(true);setMessage('保存失败，请重试');}finally{setBusy(false);}}
 return <div className="dictation-grading"><div className="dictation-grading-main"><div className="campus-toolbar"><Button intent="text" onClick={()=>{if(dirty||busy)setMessage('请先保存或放弃修改');else onBack();}}>返回任务</Button><Button onClick={()=>window.print()}>打印材料</Button></div><div className="campus-banner"><div><h3>{task.title}</h3><p>{task.date} · {task.subject} · <span className="dictation-word-count">本次 {task.words.length} 个词</span></p></div><ThemeArtwork slot="dictation"/></div><div className="dictation-student-heading"><div><small>当前{task.context.kind==='class'?'学生':'孩子'}</small><h3>{student.name} <small>{student.number}</small></h3></div>{task.context.kind==='class'&&<Button onClick={()=>setShowRoster(!showRoster)}>换学生</Button>}<span>{saved?(saved[0]==='graded'?'已批改':saved[0]==='leave'?'请假':'未参加'):'待批改'}</span></div>
 {showRoster&&<div className="dictation-mobile-roster"><label>姓名或学号<input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label>{rows.slice((page-1)*20,page*20).map(p=><Button key={p.id} onClick={()=>changeStudent(p.id)}>{p.name} {p.number}</Button>)}<Pager page={page} count={rows.length} onPage={setPage}/></div>}
 <p>由教师或家长人工报词，点选纸面写错的词。</p><fieldset disabled={readOnly||busy} className="dictation-grading-fields"><label>参与状态<select value={state} onChange={e=>{setState(e.target.value as DictationResult[0]);setDirty(true);setConfirmed(false);resultRef.current=null;}}><option value="graded">实际参与，批改</option><option value="leave">请假</option><option value="absent">未参加</option></select></label><div className="dictation-words">{task.words.map((w,i)=><label className={wrong.includes(i)&&state==='graded'?'dictation-word is-wrong':'dictation-word'} key={w.id}><span>{i+1}</span><b>{w.text}</b><small>{w.meaning}</small><input type="checkbox" aria-label={`错词 ${w.text}`} checked={state==='graded'&&wrong.includes(i)} disabled={state!=='graded'} onChange={e=>{setWrong(e.target.checked?[...wrong,i]:wrong.filter(n=>n!==i));setDirty(true);setConfirmed(false);resultRef.current=null;}}/>{wrong.includes(i)&&state==='graded'&&<em>已标错</em>}</label>)}</div><label>备注（可选）<input value={note} maxLength={300} onChange={e=>{setNote(e.target.value);setDirty(true);resultRef.current=null;}}/></label><label className="dictation-confirm"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);setDirty(true);}}/>{state==='graded'?`确认已核对全部 ${task.words.length} 个词${!wrong.length?'，本次全对':''}`:state==='leave'?'确认本次请假，不计入错误率':'确认本次未参加，不计入错误率'}</label></fieldset>
 <div role="status" aria-live="polite" className={message.includes('失败')?'dictation-error':'dictation-feedback'}>{readOnly?'当前只读，可查看记录与打印，不能提交批改。':message||'未确认前不会计入统计'}</div><footer className="dictation-savebar"><span>已标记 <b>{state==='graded'?wrong.length:0}</b> 个错词</span><Button intent="text" disabled={busy||readOnly} onClick={discard}>放弃修改</Button><Button intent="primary" disabled={!confirmed||busy||readOnly} onClick={()=>void save()}>{busy?'保存中…':task.context.kind==='class'?'保存并下一位':'保存批改'}</Button></footer>
 {saved?.[0]==='graded'&&saved[1].length>0&&<Button disabled={dirty||busy||readOnly} onClick={()=>void onReview(student)}>为{student.name}安排错词复习</Button>}
 </div>{task.context.kind==='class'&&<aside className="dictation-roster"><h3>本次学生 · {task.participants.length}人</h3><label>搜索姓名或学号<input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label className="dictation-check"><input type="checkbox" checked={pendingOnly} onChange={e=>{setPendingOnly(e.target.checked);setPage(1);}}/>只看待批改</label><div>{rows.slice((page-1)*20,page*20).map(p=><button className={p.id===studentId?'is-current':''} aria-current={p.id===studentId?'true':undefined} key={p.id} onClick={()=>changeStudent(p.id)}><span>{p.name}<small>{p.number}</small></span><small>{task.results[p.id]?(task.results[p.id][0]==='graded'?'已批改':task.results[p.id][0]==='leave'?'请假':'未参加'):'待批改'}</small></button>)}</div><Pager page={page} count={rows.length} onPage={setPage}/></aside>}</div>;
}
