'use client';
import { type DictationResult } from '@/lib/dictation';
import { Button,Pager,ThemeArtwork } from '@/app/components/campus/primitives';
import { useGradingController, type GradingProps } from '../features/dictation/useGradingController';
export function Grading(props: GradingProps) {
 const {task,readOnly,onBack,onReview}=props;
 const {query,setQuery,pendingOnly,setPendingOnly,page,setPage,wrong,setWrong,state,setState,confirmed,setConfirmed,note,setNote,dirty,setDirty,busy,message,setMessage,showRoster,setShowRoster,saved,student,rows,resultRef,changeStudent,discard,save,studentId}=useGradingController(props);
 return <div className="dictation-grading"><aside className="dictation-material-pane"><div className="dictation-material-actions"><Button intent="text" onClick={()=>{if(dirty||busy)setMessage('请先保存或放弃修改');else onBack();}}>返回任务</Button><Button intent="text" onClick={()=>window.print()}>打印</Button></div><ThemeArtwork slot="dictation"/><span>{task.subject}</span><h2>{task.title}</h2><p>{task.date} · {task.words.length} 个词</p><dl><div><dt>参与</dt><dd>{task.participants.length}人</dd></div><div><dt>已完成</dt><dd>{Object.keys(task.results).length}人</dd></div></dl><div className="dictation-material-preview"><b>本次材料</b>{task.words.slice(0,8).map((word,index)=><span key={word.id}>{index+1}. {word.text}</span>)}{task.words.length>8&&<small>另有 {task.words.length-8} 个词</small>}</div></aside><div className="dictation-grading-main"><div className="campus-toolbar"><Button intent="text" onClick={()=>{if(dirty||busy)setMessage('请先保存或放弃修改');else onBack();}}>返回任务</Button><Button onClick={()=>window.print()}>打印材料</Button></div><div className="campus-banner"><div><h3>{task.title}</h3><p>{task.date} · {task.subject} · <span className="dictation-word-count">本次 {task.words.length} 个词</span></p></div><ThemeArtwork slot="dictation"/></div><div className="dictation-student-heading"><div><small>当前{task.context.kind==='class'?'学生':'孩子'}</small><h3>{student.name} <small>{student.number}</small></h3></div>{task.context.kind==='class'&&<Button onClick={()=>setShowRoster(!showRoster)}>换学生</Button>}<span>{saved?(saved[0]==='graded'?'已批改':saved[0]==='leave'?'请假':'未参加'):'待批改'}</span></div>
 {showRoster&&<div className="dictation-mobile-roster"><label>姓名或学号<input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label>{rows.slice((page-1)*20,page*20).map(p=><Button key={p.id} onClick={()=>changeStudent(p.id)}>{p.name} {p.number}</Button>)}<Pager page={page} count={rows.length} onPage={setPage}/></div>}
 <p>由教师或家长人工报词，点选纸面写错的词。</p><fieldset disabled={readOnly||busy} className="dictation-grading-fields"><label>参与状态<select value={state} onChange={e=>{setState(e.target.value as DictationResult[0]);setDirty(true);setConfirmed(false);resultRef.current=null;}}><option value="graded">实际参与，批改</option><option value="leave">请假</option><option value="absent">未参加</option></select></label><div className="dictation-words">{task.words.map((w,i)=><label className={wrong.includes(i)&&state==='graded'?'dictation-word is-wrong':'dictation-word'} key={w.id}><span>{i+1}</span><b>{w.text}</b><small>{w.meaning}</small><input type="checkbox" aria-label={`错词 ${w.text}`} checked={state==='graded'&&wrong.includes(i)} disabled={state!=='graded'} onChange={e=>{setWrong(e.target.checked?[...wrong,i]:wrong.filter(n=>n!==i));setDirty(true);setConfirmed(false);resultRef.current=null;}}/>{wrong.includes(i)&&state==='graded'&&<em>已标错</em>}</label>)}</div><label>备注（可选）<input value={note} maxLength={300} onChange={e=>{setNote(e.target.value);setDirty(true);resultRef.current=null;}}/></label><label className="dictation-confirm"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);setDirty(true);}}/>{state==='graded'?`确认已核对全部 ${task.words.length} 个词${!wrong.length?'，本次全对':''}`:state==='leave'?'确认本次请假，不计入错误率':'确认本次未参加，不计入错误率'}</label></fieldset>
 <div role="status" aria-live="polite" className={message.includes('失败')?'dictation-error':'dictation-feedback'}>{readOnly?'当前只读，可查看记录与打印，不能提交批改。':message||'未确认前不会计入统计'}</div><footer className="dictation-savebar"><span>已标记 <b>{state==='graded'?wrong.length:0}</b> 个错词</span><Button intent="text" disabled={busy||readOnly} onClick={discard}>放弃修改</Button><Button intent="primary" disabled={!confirmed||busy||readOnly} onClick={()=>void save()}>{busy?'保存中…':task.context.kind==='class'?'保存并下一位':'保存批改'}</Button></footer>
 {saved?.[0]==='graded'&&saved[1].length>0&&<Button disabled={dirty||busy||readOnly} onClick={()=>void onReview(student)}>为{student.name}安排错词复习</Button>}
 </div>{task.context.kind==='class'&&<aside className="dictation-roster"><h3>本次学生 · {task.participants.length}人</h3><label>搜索姓名或学号<input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label className="dictation-check"><input type="checkbox" checked={pendingOnly} onChange={e=>{setPendingOnly(e.target.checked);setPage(1);}}/>只看待批改</label><div>{rows.slice((page-1)*20,page*20).map(p=><button className={p.id===studentId?'is-current':''} aria-current={p.id===studentId?'true':undefined} key={p.id} onClick={()=>changeStudent(p.id)}><span>{p.name}<small>{p.number}</small></span><small>{task.results[p.id]?(task.results[p.id][0]==='graded'?'已批改':task.results[p.id][0]==='leave'?'请假':'未参加'):'待批改'}</small></button>)}</div><Pager page={page} count={rows.length} onPage={setPage}/></aside>}</div>;
}
