'use client';
import { useMemo,useRef,useState } from 'react';
import type { ClassroomData } from '@/lib/classroom';
import { newTask,parseWords,today,wrongWords,contextKey,type DictationTask,type LearningContext,type Participant,type WordEntry } from '@/lib/dictation';
import { Button,Pager } from '@/app/components/campus/primitives';
export function TaskEditor({ data,context,participants,initial,onSave,onCancel,readOnly }: { data:ClassroomData;context:LearningContext;participants:Participant[];initial?:DictationTask;onSave:(t:DictationTask)=>Promise<boolean>;onCancel:()=>void;readOnly:boolean }) {
 const books=data.dictation?.books??[];
 const [bookId,setBookId]=useState(initial?.bookId??''),[lesson,setLesson]=useState(initial?.lesson??''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<string[]>(initial?.participants.map(p=>p.id)??(context.kind==='family'?participants.map(p=>p.id):[])),[content,setContent]=useState(initial?.words.map(w=>`${w.text} | ${w.meaning} | ${w.lesson}`).join('\n')??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [retrying,setRetrying]=useState(false);
 const [reviewWords,setReviewWords]=useState<WordEntry[]>([]);
 const pending=useRef<DictationTask|null>(null);
 const book=books.find(b=>b.id===bookId),lessons=[...new Set(book?.entries.map(w=>w.lesson)??[])];
 const words=useMemo(()=>{try{return [...(book?book.entries.filter(w=>!lesson||w.lesson===lesson):parseWords(content)),...reviewWords];}catch{return [];}},[book,lesson,content,reviewWords]);
 const rows=participants.filter(p=>`${p.name} ${p.number}`.toLowerCase().includes(query.toLowerCase()));
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy||readOnly)return;const f=new FormData(e.currentTarget);setError('');try{const uniqueWords:WordEntry[]=[];const seen=new Set<string>();for(const w of words){const key=w.text.toLowerCase();if(!seen.has(key)){seen.add(key);uniqueWords.push(w);}}
 const task=pending.current??newTask({title:String(f.get('title')).trim(),date:String(f.get('date')),subject:String(f.get('subject')),context,participants:participants.filter(p=>selected.includes(p.id)),words:uniqueWords,...(bookId?{bookId,lesson}:{}),...(String(f.get('homeworkId')??'')?{homeworkId:String(f.get('homeworkId'))}:{})});
 const final=initial?{...task,id:initial.id,createdAt:initial.createdAt}:task;pending.current=final;setRetrying(true);setBusy(true);if(await onSave(final))pending.current=null;else setError('保存失败，内容已保留；重试不会重复创建任务。');}catch(e){setError(e instanceof Error?e.message:'创建失败');}finally{setBusy(false);}}
 return <form className="dictation-form" onSubmit={submit}><h3>{initial?'编辑任务':'新建听写'}</h3><fieldset disabled={busy||readOnly||retrying}><div className="dictation-form-grid"><label>任务名称<input name="title" required maxLength={120} defaultValue={initial?.title}/></label><label>日期<input type="date" name="date" required defaultValue={initial?.date??today()}/></label><label>学科<select name="subject" defaultValue={initial?.subject??'英语'}><option>英语</option><option>语文</option><option>成语</option><option>自定义</option></select></label><label>材料来源<select value={bookId} onChange={e=>{setBookId(e.target.value);setLesson('');}}><option value="">自定义文本</option>{books.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label>{book&&<label>课次 / 词组<select value={lesson} onChange={e=>setLesson(e.target.value)}><option value="">全部课次</option>{lessons.map(l=><option key={l}>{l}</option>)}</select></label>}{context.kind==='class'&&<label>关联作业（可选）<select name="homeworkId" defaultValue={initial?.homeworkId??''}><option value="">不关联</option>{data.homeworkTasks?.filter(t=>t.classId===context.classId).map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label>}</div>{!book&&<label>听写内容<textarea rows={6} value={content} onChange={e=>setContent(e.target.value)} placeholder={'每行：词语 | 释义 | 课次\napple | 苹果 | 第1课'} required={!reviewWords.length}/></label>}<div className="campus-toolbar"><Button disabled={!selected.length} onClick={e=>{const subject=String(new FormData(e.currentTarget.form!).get("subject"));const tasks=(data.dictation?.tasks??[]).filter(t=>contextKey(t.context)===contextKey(context)&&t.subject===subject);setReviewWords(wrongWords(tasks).filter(w=>selected.includes(w.participant.id)).map(w=>w.word));}}>加入参与者历史错词</Button>{reviewWords.length>0&&<><span>已加入 {reviewWords.length} 个错词，保存时自动去重</span><Button intent="text" onClick={()=>setReviewWords([])}>移除追加错词</Button></>}</div><p>材料预览：去重前 {words.length} 个词（每次最多200词）。任务建立后使用独立材料快照。</p><div className="dictation-preview">{words.slice(0,200).map((w,i)=><span key={`${w.id}-${i}`}>{w.text}</span>)}</div>
 {context.kind==='class'&&<><div className="campus-toolbar"><label>搜索参与学生<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="姓名或学号"/></label><Button onClick={()=>setSelected([...new Set([...selected,...rows.map(p=>p.id)])])}>选择筛选结果（{rows.length}）</Button><Button intent="text" onClick={()=>setSelected([])}>清空选择</Button></div><p>已选 {selected.length} 人 / 名册 {participants.length} 人</p><div className="dictation-participant-picker">{rows.slice((page-1)*20,page*20).map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/><span>{p.name}<small>{p.number}</small></span></label>)}</div><Pager page={page} count={rows.length} onPage={setPage}/></>}
 {context.kind==='family'&&<p>本次孩子：{participants[0]?.name??'请先建立孩子档案'}</p>}</fieldset>{error&&<p className="dictation-error" role="alert">{error}</p>}<div className="campus-actions"><Button disabled={busy} onClick={onCancel}>返回任务</Button><Button type="submit" intent="primary" disabled={busy||readOnly}>{busy?'保存中…':retrying?'重试保存':'保存任务'}</Button></div></form>;
}
