'use client';
import { useRef, useState } from 'react';
import { makeId } from '@/lib/classroom';
import { parseWords, type WordBook } from '@/lib/dictation';
import { Button, EmptyState, Pager } from '@/app/components/campus/primitives';
export function WordLibrary({ books, readOnly, save, remove }: { books:WordBook[]; readOnly:boolean; save:(book:WordBook)=>Promise<boolean>; remove:(id:string)=>Promise<void> }) {
 const [editing,setEditing]=useState<WordBook|null>(null),[creating,setCreating]=useState(false),[query,setQuery]=useState(''),[page,setPage]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const newBookId=useRef('');
 const rows=books.filter(b=>`${b.title} ${b.subject} ${b.grade}`.includes(query));
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy||readOnly)return;const form=new FormData(e.currentTarget);try{const title=String(form.get('title')).trim();if(!title)throw new Error('请填写词库名称');const entries=parseWords(String(form.get('words')));if(!entries.length)throw new Error('请至少填写一个词');setBusy(true);const book:WordBook={id:editing?.id??(newBookId.current ||= makeId('book')),title,subject:String(form.get('subject')),edition:String(form.get('edition')),grade:String(form.get('grade')),term:String(form.get('term')),entries};if(await save(book)){setEditing(null);setCreating(false);newBookId.current='';setError('');}}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 if(creating||editing)return <form className="dictation-form" onSubmit={submit}><h3>{editing?'编辑词库':'建立词库'}</h3><p>每行一个词，可用竖线分隔：词语 | 释义 | 课次。同课次重复词自动去重。</p><div className="dictation-form-grid"><label>词库名称<input name="title" required maxLength={120} defaultValue={editing?.title}/></label><label>学科<select name="subject" defaultValue={editing?.subject??'英语'}><option>英语</option><option>语文</option><option>成语</option><option>自定义</option></select></label><label>教材版本<input name="edition" maxLength={120} defaultValue={editing?.edition}/></label><label>年级<input name="grade" maxLength={80} defaultValue={editing?.grade}/></label><label>学期<input name="term" maxLength={80} defaultValue={editing?.term}/></label></div><label>文本内容<textarea name="words" required rows={10} defaultValue={editing?.entries.map(w=>`${w.text} | ${w.meaning} | ${w.lesson}`).join('\n')}/></label><label>导入TXT文件<input type="file" accept=".txt,text/plain" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>512*1024){setError('文本最多512KB，请分批导入');return;}const area=e.target.form?.elements.namedItem('words') as HTMLTextAreaElement;if(area)area.value=await f.text();}}/></label>{error&&<p role="alert">{error}</p>}<div className="campus-actions"><Button disabled={busy} onClick={()=>{setCreating(false);setEditing(null);}}>取消</Button><Button type="submit" intent="primary" disabled={busy||readOnly}>{busy?'保存中…':'保存词库'}</Button></div></form>;
 return <><div className="campus-toolbar"><label>搜索词库<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="名称、学科或年级"/></label><Button intent="primary" disabled={readOnly} onClick={()=>{newBookId.current='';setError('');setCreating(true);}}>建立词库 / 导入文本</Button></div>{!rows.length?<EmptyState>还没有匹配的词库。可手动建立或导入TXT文本。</EmptyState>:<div className="dictation-table-scroll"><table><thead><tr><th>词库</th><th>学科 / 年级</th><th>课次 / 词数</th><th>操作</th></tr></thead><tbody>{rows.slice((page-1)*20,page*20).map(b=><tr key={b.id}><td>{b.title}<small>{b.edition} {b.term}</small></td><td>{b.subject} {b.grade}</td><td>{new Set(b.entries.map(w=>w.lesson)).size}课 / {b.entries.length}词</td><td><Button intent="text" disabled={readOnly} onClick={()=>{setError('');setEditing(b);}}>编辑</Button><Button intent="danger" disabled={readOnly} onClick={()=>void remove(b.id)}>删除</Button></td></tr>)}</tbody></table></div>}<Pager page={page} count={rows.length} onPage={setPage}/></>;
}
