import {scoresFixture} from './scores-fixture';
import {saveExamReflection} from '../../app/w/[token]/features/reflections/operations';
export const reflectionStates=['normal','saved-long-labels','saved-detail','saved-empty','saved-search-empty','saved-long-detail','saved-readonly','legacy-library','mobile-editor','saved-library','empty-class','no-exams','search-empty','students-105','long-exams','readonly','loading','saving','save-failure','save-throw','conflict-409','dirty-close','exam-picker','score-detail'];
export function reflectionFixture(state:string){let data=scoresFixture(state==='students-105'?'students-105':'normal');data.examReflections=[];data.records=[];
 const ex=data.scoreExams![0];ex.scores[data.students[0].id]={语文:82,数学:78,英语:80};
 for(let i=0;i<8;i++){const result=saveExamReflection(data,'class-1',{id:'reflection-'+i,studentId:data.students[i].id,examId:ex.id,date:'2026-09-15',problem:['审题漏看条件。','计算步骤记录不完整。','解题后没有核对单位。','阅读题依据提取不完整。','表达顺序不够清楚。','解答时漏写关键步骤。','需要练习复述解题思路。','需要补充对应考试背景。'][i],reason:'先听学生复述思路，再核对出错环节。',action:['每天订正一道错题，周五复查。','保留中间步骤再核对。','完成后逐项核对单位。','圈画依据后再组织答案。','先列要点再完整表达。','先复述步骤，再独立练习。','讲清依据，周五复查。','与学生一起核对原记录。'][i],familyMessage:'每天留十分钟，让孩子讲一道题的思路。',teacherNote:'周五查看订正情况，再调整练习安排。'},i<3?'草稿':'已完成',()=> 'reflection-'+i,()=> 'archive-'+i);if(result.data)data=result.data;}
 if(['saved-library','saved-detail','saved-search-empty','saved-long-detail','saved-readonly'].includes(state)){const older={...structuredClone(ex),id:'p02-older',title:'单元练习',date:'2026-09-10'};data.scoreExams!.push(older);const previous=data.examReflections!.find(r=>r.studentId===data.students[2].id)!;previous.examId=older.id;previous.date='2026-09-12';const unlinked=data.examReflections!.find(r=>r.studentId===data.students[7].id)!;unlinked.examId=undefined;unlinked.date='2026-09-08';const r=data.examReflections!.find(r=>r.studentId===data.students[3].id)!;Object.assign(r,{problem:'阅读题中遗漏了关键条件，回答时没有写清依据。',reason:'先看了问题就急于作答，没有回到原文逐句核对。',action:'每天选一段短文，先圈出问题中的关键词，再标出原文依据。周五复查两道同类题。',familyMessage:'请让孩子讲清答案是从哪一句话找到的，不急于提示答案。',teacherNote:'周五查看练习中的依据标注，记录学生能否独立复述解题过程。'});if(state==='saved-long-detail')r.teacherNote=r.teacherNote.repeat(25);}
 if(state==='saved-empty')data.examReflections=[];
 if(state==='saved-long-labels'){data.students[0].name='学生01合成长姓名用于验证换行';data.rosterClasses![0].students[0].name=data.students[0].name;data.scoreExams!.find(e=>e.id===ex.id)!.title='本学期跨学科项目阶段综合练习与学习方法回顾合成考试名称';}
 if(state==='empty-class'){data.students=[];data.rosterClasses![0].students=[];data.examReflections=[];}if(state==='no-exams'){data.scoreExams=[];data.examReflections=[];}
 if(state==='students-105'){data.students[0].name='学生01合成长姓名用于验证换行';data.rosterClasses![0].students[0].name=data.students[0].name;data.examReflections![0].teacherNote='本段为合成长内容，用于检查文本换行和草稿保留。'.repeat(30);}
 if(['long-exams','exam-picker'].includes(state)){data.scoreExams=Array.from({length:35},(_,i)=>({...structuredClone(ex),id:i===0?ex.id:'exam-'+i,title:'第'+(i+1)+'次综合练习与跨学科项目阶段回顾',date:'2026-'+String(1+i%9).padStart(2,'0')+'-15'}));}
 if(state==='legacy-library'){data.scoreExams!.push({...structuredClone(ex),id:'older-exam',title:'上次综合练习'});data.examReflections!.push({...structuredClone(data.examReflections![0]),id:'legacy-reflection',studentId:data.students[8].id,examId:undefined,reason:'合成历史原因检索证据'});data.examReflections!.push({...structuredClone(data.examReflections![0]),id:'older-reflection',studentId:data.students[9].id,examId:'older-exam'});}
 return data;
}
