import {homeworkFixture} from './homework-fixture';
export const scoresStates=['review','analysis-many','student-trends','trend-single','trend-empty','trend-no-exams','analysis-empty','analysis-readonly','normal','mobile-detail','empty-class','no-exams','search-empty','students-105','long-subjects','mixed-max','composer','student-editor','batch','ranges','readonly','loading','saving','save-failure','save-throw','conflict-409','dirty-close','trends','long-history','analysis','paper-review','ai-failure','item-editor','item-scores'];
export function scoresFixture(state:string):ReturnType<typeof homeworkFixture>{if(state==='review'){const data=scoresFixture('student-trends'),analysis=scoresFixture('analysis').scoreExams![0];data.scoreExams![data.scoreExams!.length-1].knowledgeItems=analysis.knowledgeItems;data.scoreExams![data.scoreExams!.length-1].paperAnalyses=analysis.paperAnalyses;data.scoreExams!.reverse();return data;}const data=homeworkFixture(state==='students-105'?'students-105':'normal');data.activeClassId='class-1';data.scoreExams=[{id:'synthetic-score-1',classId:'class-1',title:'9月综合练习',date:'2026-09-15',subjects:['语文','数学','英语'],subjectMaxScores:{语文:100,数学:100,英语:100},scores:Object.fromEntries(data.students.map((s,i)=>[s.id,{语文:80+i%16,数学:i===2?0:82+i%14,...(i===1?{}:{英语:78+i%18})}])),followUpStudentIds:[data.students[2].id]}];
const exam=data.scoreExams![0];
if(state==='long-subjects'){const name='综合实践与跨学科学习长科目';exam.subjects.push(name);exam.subjectMaxScores![name]=120;data.students[0].name='学生01合成长姓名展示';}
if(state==='mixed-max'){exam.subjectMaxScores={语文:120,数学:100,英语:50};for(const scores of Object.values(exam.scores))if(scores.英语!=null)scores.英语=Math.round(scores.英语/2);}
if(['trends','long-history'].includes(state)){data.scoreExams=Array.from({length:state==='long-history'?50:5},(_,i)=>({...structuredClone(exam),id:'history-'+i,title:'合成练习 '+(i+1),date:new Date(Date.UTC(2026,0,1+i*4)).toISOString().slice(0,10),scores:i===2?{}:Object.fromEntries(data.students.map(st=>[st.id,{语文:70+i%20,数学:80,英语:40}])),subjectMaxScores:{语文:100,数学:100,英语:50}}));}
if(['analysis','paper-review','ai-failure','item-scores'].includes(state)){exam.knowledgeItems=[{id:'synthetic-item-1',title:'阅读信息提取',subject:'语文',questionNo:'1',knowledgePoint:'提取事实',maxScore:10,scores:{[data.students[0].id]:8,[data.students[1].id]:0},source:'teacher'}];exam.paperAnalyses=[{id:'synthetic-paper',sourceName:'合成阅读练习.pdf',sourceType:'application/pdf',sourceSize:102400,createdAt:'2026-09-15T01:00:00Z',status:state==='ai-failure'?'失败':'待核对',message:state==='ai-failure'?'合成错误：识别服务不可用，请重新选择文件预览。':'合成候选，未上传真实文件。',items:[{id:'synthetic-candidate',title:'阅读理解',questionNo:'2',subject:'语文',knowledgePoint:'信息归纳',maxScore:10,scores:{},source:'ai',confidence:.82}]}];}
if(['trends','student-trends'].includes(state)){data.scoreExams=Array.from({length:6},(_,i)=>({...structuredClone(exam),id:'history-'+i,title:'9月练习'+(i+1),date:'2026-09-'+String(1+i*2).padStart(2,'0'),scores:i===2?{}:Object.fromEntries(data.students.map((st,j)=>[st.id,j===0?(i===5?{语文:86,数学:82,英语:84}:i===3?({语文:78,数学:78} as Record<string,number>):{语文:[70,74,0,78,80,84][i],数学:[70,74,0,78,80,84][i],英语:[70,74,0,78,80,84][i]}):{语文:[76,78,0,80,79,82][i],数学:[76,78,0,80,79,82][i],英语:[76,78,0,80,79,82][i]}]))}));}
if(state==='trend-empty')exam.scores={};
if(state==='trend-no-exams')data.scoreExams=[];
if(['analysis','analysis-readonly','analysis-many'].includes(state)){exam.knowledgeItems=[{id:'synthetic-item-1',title:'信息提取',subject:'语文',knowledgePoint:'信息提取',maxScore:10,scores:Object.fromEntries(data.students.map(st=>[st.id,8])),source:'teacher'},{id:'synthetic-item-2',title:'句段理解',subject:'语文',knowledgePoint:'句段理解',maxScore:10,scores:Object.fromEntries(data.students.slice(0,24).map(st=>[st.id,6])),source:'teacher'},{id:'synthetic-item-3',title:'表达应用',subject:'语文',knowledgePoint:'表达应用',maxScore:5,scores:{},source:'teacher'}];exam.paperAnalyses=[{id:'synthetic-paper',sourceName:'9月阅读练习.pdf',sourceType:'application/pdf',sourceSize:102400,createdAt:'2026-09-15T01:00:00Z',status:'待核对',items:[{id:'c-4',title:'概括段意',subject:'语文',questionNo:'4',knowledgePoint:'信息归纳',maxScore:5,scores:{},source:'ai'},{id:'c-5',title:'表达观点',subject:'语文',questionNo:'5',knowledgePoint:'观点表达',maxScore:5,scores:{},source:'ai'}]},{id:'paper-complete',sourceName:'数学练习.png',sourceType:'image/png',sourceSize:204800,createdAt:'2026-09-15T01:00:00Z',status:'已确认',items:[]}];}
if(state==='analysis-many')exam.paperAnalyses=Array.from({length:21},(_,i)=>({...structuredClone(exam.paperAnalyses![0]),id:'paper-many-'+i,sourceName:'合成试卷'+(i+1)+'.pdf'}));
if(state==='no-exams')data.scoreExams=[];
if(state==='empty-class'){data.students=[];data.rosterClasses![0].students=[];data.scoreExams=[];}
return data;}
