import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {ClassroomData} from '../../lib/classroom';
import {ScoresDesign} from '../../app/designs/scores/ScoresDesign';
import {useScoresDesignController} from '../../app/designs/scores/useScoresDesignController';
import {WorkbenchShell} from '../../app/components/workbench/shell/WorkbenchShell';
import {scoresFixture,scoresStates} from './scores-fixture';
import './students-preview.css';
const RealDate=Date,frozen=RealDate.parse('2026-09-15T09:00:00+08:00');
globalThis.Date=new Proxy(RealDate,{construct:(target,args)=>Reflect.construct(target,args.length?args:[frozen]),get:(target,key)=>key==='now'?()=>frozen:Reflect.get(target,key)});
const scenario=new URLSearchParams(location.search).get('state')||'normal';
function Preview(){
 const [data,setData]=useState(()=>scoresFixture(scenario)),[mobile,setMobile]=useState(innerWidth<=900),[sync,setSync]=useState('normal');const attempts=useRef(0),initialized=useRef(false),submitted=useRef(false);const readOnly=scenario==='readonly';
 const update=(fn:(d:ClassroomData)=>ClassroomData)=>{if(!readOnly)setData(fn);};
 const save=async()=>{if(readOnly)return false;attempts.current++;setSync('saving');await new Promise(r=>setTimeout(r,scenario==='saving'?60000:400));const fail=scenario==='conflict-409'||attempts.current===1&&['save-failure','save-throw','delete-failure'].includes(scenario);setSync(fail?scenario:'normal');if(fail&&scenario==='save-throw')throw Error('synthetic network interruption');return !fail;};
 const exportDraft=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.href=url;a.download='synthetic-scores-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const loadLatest=()=>location.assign('scores.html?state=normal');
 const c=useScoresDesignController({data,update,save,readOnly,mobile,conflict:sync==='conflict-409',exportDraft,loadLatest});
 useEffect(()=>{const media=matchMedia('(max-width:900px)');const changed=()=>setMobile(media.matches);media.addEventListener('change',changed);return()=>media.removeEventListener('change',changed);},[]);
 useEffect(()=>{if(initialized.current)return;initialized.current=true;if(scenario==='search-empty')c.setQuery('不存在');if(['trends','long-history'].includes(scenario))c.switchTab('trends');if(['analysis','paper-review','ai-failure','item-scores'].includes(scenario))c.switchTab('analysis');if(['mobile-detail','student-editor'].includes(scenario))c.openStudent(c.students[1]);if(['composer','dirty-close','saving','save-failure','save-throw','conflict-409'].includes(scenario))c.openExam();if(scenario==='ranges')c.begin('ranges',{subject:'语文',max:'100',ranges:JSON.stringify([{id:'pass',label:'60%以上',min:60,max:100}])});if(scenario==='batch'){c.setSelected(c.students.slice(0,3).map(s=>s.id));c.begin('batch',{subject:'数学',value:'85'});}if(scenario==='item-editor')c.begin('item',{title:'',subject:'语文',questionNo:'',knowledgePoint:'',questionType:'',max:'10'});if(scenario==='paper-review')c.begin('paper',{id:'synthetic-paper'},structuredClone(c.exam.paperAnalyses![0].items!));if(scenario==='item-scores')c.begin('item-scores',{id:'synthetic-item-1',...Object.fromEntries(c.students.map(st=>[st.id,String(c.exam.knowledgeItems![0].scores[st.id]??'')]))});},[c]);
 useEffect(()=>{if(submitted.current||!c.editor)return;if(['saving','save-failure','save-throw','conflict-409','dirty-close'].includes(scenario)){if(!c.editor.fields.title){c.setField('title','合成新考试');return;}submitted.current=true;if(scenario==='dirty-close')c.closeEditor();else void c.saveEditor();}},[c]);
 useEffect(()=>{Object.assign(window,{__scores:{getData:()=>data,controller:c,getState:()=>({busy:c.busy,dirty:c.dirty,pending:c.pending,sync,editor:c.editor?.kind,selected:c.exam?.id})}});},[c,data,sync]);
 const navigate=()=>{if(window.dispatchEvent(new Event('classroom:before-navigate',{cancelable:true})))c.setMessage('独立成绩设计稿：当前仅含合成数据。');};
 const surface=scenario==='loading'?<p className="design-loading" role="status">正在加载成绩分析…</p>:<ScoresDesign controller={c}/>;
 return <><script id="scores-design-fixture" type="application/json">{JSON.stringify(scoresFixture(scenario))}</script><WorkbenchShell active="scores" scene="class" classes={data.rosterClasses!} activeClass={data.rosterClasses![0]} workspaceGrade="三年级" saving={sync==='saving'} dirty={c.dirty||c.pending} error={sync==='conflict-409'?'版本冲突，草稿已保留。':['save-failure','save-throw','delete-failure'].includes(sync)?'保存失败，草稿已保留。':''} isDemo={false} isReadOnly={readOnly} desktopContent={!mobile?surface:null} mobileContent={mobile?surface:null} onOpen={navigate} onBack={navigate} onSwitchClass={navigate} onScene={navigate} onAccount={navigate} onRetrySave={()=>void c.sync()} onClearError={()=>{}} saveConflict={sync==='conflict-409'} onExportDraft={()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.href=url;a.download='synthetic-scores-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}} onLoadLatest={()=>location.reload()}/><details className="design-controls"><summary>设计预览 · 合成数据</summary><label>查看状态<select aria-label="预览状态" value={scenario} onChange={e=>location.assign(`scores.html?state=${e.target.value}`)}>{scoresStates.map(v=><option key={v}>{v}</option>)}</select></label><p>仅内存数据，保存/失败/409为模拟；刷新恢复。</p></details></>;
}
createRoot(document.getElementById('root')!).render(<Preview/>);
