import {useState} from 'react';
import {Dialog} from '@/app/components/workbench/ui/Dialog';
import {ThemeBoundary} from '@/app/components/workbench/theme/ThemeBoundary';
import {StudentLookupDialog} from '@/app/components/campus/StudentLookupDialog';
import {CampusIcon} from '@/app/components/campus/primitives';
import {categories,contexts,categoryLabel,type useHealthDesignController} from './useHealthDesignController';
import art from './care-p01.png';
import s from './HealthDesign.module.css';
type Controller=ReturnType<typeof useHealthDesignController>;
export function HealthDesign({controller:c}:{controller:Controller}){
 const [filtersOpen,setFiltersOpen]=useState(false),[contactId,setContactId]=useState(''),[more,setMore]=useState(false),[picker,setPicker]=useState(false),[replace,setReplace]=useState(false);
 const p=c.selected,student=c.students.find(v=>v.id===p?.studentId),draft=c.draft;
 const filters=<div className={s.filters}>{(['severity','category','context'] as const).map((key,i)=><label key={key}><span>{['优先级','关注类型','适用场景'][i]}</span><select aria-label={['优先级','关注类型','适用场景'][i]} value={c.filters[key]} onChange={e=>c.changeFilter(key,e.target.value)}><option value="全部">{['全部优先级','全部类型','全部场景'][i]}</option>{(key==='severity'?['紧急','重要','一般']:key==='category'?categories:c.availableContexts).map(v=><option key={v}>{v}</option>)}</select></label>)}<button onClick={c.reset}>重置筛选</button></div>;
 const contact=(id:string)=>{const g=c.guardian(id);return g?`${g.name}${g.relation?`（${g.relation}）`:''}${g.phone?` · ${g.phone}`:''}`:'学生名单中暂未维护监护人联系方式';};
 return <section className={s.page} data-health-design="page" data-mobile={c.mobile||undefined}>
 {(!c.mobile||!c.detailOpen)&&<><header className={s.heading}><div><h1>健康与照护</h1><p>日常安排前，查看必要行动提示。</p><span>{new Set(c.profiles.map(v=>v.studentId)).size}名学生已登记 · {c.profiles.filter(v=>v.severity!=='一般').length}条需优先留意 · 仅班主任查看</span></div><img src={typeof art==='string'?art:art.src} alt="" width="1536" height="1024"/>{!c.mobile&&<button className={s.primary} disabled={c.readOnly||!c.students.length} onClick={()=>c.openEditor()}><CampusIcon name="plus"/>新增照护登记</button>}</header><div className={s.toolbar}><label className={s.search}><CampusIcon name="search"/><input aria-label="搜索学生或行动提示" placeholder="学生或行动提示" value={c.filters.query} onChange={e=>c.changeFilter('query',e.target.value)}/></label>{c.mobile?<button aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(!filtersOpen)}>筛选</button>:filters}</div>{c.mobile&&filtersOpen&&filters}{c.mobile&&<nav className={s.quick} aria-label="快捷场景">{['全部','体育活动','座位安排'].map(v=><button key={v} aria-pressed={c.filters.context===v} onClick={()=>c.changeFilter('context',v)}>{v==='全部'?'全部场景':v}</button>)}</nav>}</>}
 {c.message&&<p className={s.message} role="status">{c.message}<button onClick={()=>c.setMessage('')}>关闭提示</button></p>}
 <div className={s.layout}>{(!c.mobile||!c.detailOpen)&&<section className={s.list}><header className={s.listTitle}><h2>照护行动清单</h2>{c.mobile&&<button disabled={c.readOnly||!c.students.length} onClick={()=>c.openEditor()}><CampusIcon name="plus"/>新增登记</button>}</header>{c.rows.map(item=>{const st=c.students.find(v=>v.id===item.studentId);return <button key={item.id} className={s.row} data-care-id={item.id} aria-pressed={p?.id===item.id} onClick={()=>{c.select(item.id);setMore(false);}}><span className={s.identity}><b>{st?.name} <small>· 学号{st?.studentNo||'未填'}</small></b><span className={s.level} data-level={item.severity}>{item.severity}</span></span><span className={s.action}><strong>{item.summary||categoryLabel(item)}</strong><span>{item.instruction||'暂未填写行动说明'}</span><small>{item.actionContexts?.map(v=><em key={v}>{v}</em>)}<span>最近确认 {item.reviewedAt||'未填写'}</span></small></span><CampusIcon name="chevron"/></button>;})}{!c.rows.length&&<div className={s.empty}><h3>{!c.students.length?'先建立学生名单':c.profiles.length?'没有符合筛选条件的记录':'尚未建立照护登记'}</h3><p>{c.profiles.length?'调整筛选，重新查看行动提示。':'仅记录日常安排必需的信息。'}</p>{c.profiles.length>0&&<button onClick={c.reset}>清除搜索和筛选</button>}</div>}<nav className={s.pagination} aria-label="照护记录分页"><span>共{c.shown.length}条记录</span>{c.pages>1&&<><button disabled={c.safePage===1} onClick={()=>c.setPage(v=>v-1)}>上一页</button><span>{c.safePage}/{c.pages}</span><button disabled={c.safePage===c.pages} onClick={()=>c.setPage(v=>v+1)}>下一页</button></>}</nav></section>}
 {(!c.mobile||c.detailOpen)&&<aside className={s.detail} aria-label="照护详情">{c.mobile&&<button className={s.back} onClick={()=>c.setDetailOpen(false)}>返回行动清单</button>}{p?<><h2>{student?.name} · 学号{student?.studentNo||'未填'}</h2><p>{categoryLabel(p)} <span className={s.level} data-level={p.severity}>{p.severity}</span></p>{p.summary&&<h3 className={s.actionSummary}>{p.summary}</h3>}<h3>老师需要做什么</h3><p>{p.instruction||'暂未填写行动说明'}</p><h3>注意事项</h3><p>{p.contraindication||'暂未填写注意事项'}</p><h3>适用场景</h3><div className={s.tags}>{p.actionContexts?.length?p.actionContexts.map(v=><span key={v}>{v}</span>):'暂未填写适用场景'}</div><p className={s.date}><b>最近确认</b>{p.reviewedAt||'未填写'}</p><div className={s.contact}><button aria-expanded={contactId===p.id} onClick={()=>setContactId(contactId===p.id?'':p.id)}>{contactId===p.id?'收起联系人信息':'查看联系人信息'}</button>{contactId===p.id&&<p>{contact(p.studentId)}</p>}</div><footer><button className={s.primary} disabled={c.readOnly} onClick={()=>c.openEditor(p)}>编辑登记</button><button disabled={c.readOnly} aria-expanded={more} onClick={()=>setMore(!more)}>更多</button>{more&&<button className={s.danger} onClick={()=>{c.openEditor(p);c.setConfirmDelete(true);setMore(false);}}>删除记录</button>}</footer></>:<p>选择一条登记查看行动提示。</p>}</aside>}</div>
 <p className={s.footnote}>仅记录日常安排所需的信息；敏感原件按学校制度线下保管。</p>
 <ThemeBoundary>{draft&&<Dialog open title={draft.id?'编辑照护登记':'新增照护登记'} description="先选择学生，再按需要补充提示。弹窗视觉待专项补审。" busy={c.busy} dirty={c.dirty} onRequestClose={c.requestClose} footer={<><button disabled={c.busy} onClick={c.requestClose}>取消</button><button disabled={c.busy||c.readOnly} onClick={()=>void c.persist()}>{c.busy?'保存中…':c.pending?'重试同步':'保存登记'}</button></>}><fieldset className={s.editor} disabled={c.readOnly||c.busy||!!c.pending}><label>学生（必选）<button type="button" onClick={()=>setPicker(true)}>{c.students.find(v=>v.id===draft.studentId)?.name||'搜索姓名或学号选择学生'}</button></label><div className={s.formGrid}><label>关注类型<select aria-label="编辑关注类型" value={draft.category} onChange={e=>c.setDraft({...draft,category:e.target.value as typeof draft.category})}>{categories.map(v=><option key={v}>{v}</option>)}</select></label><label>优先级<select aria-label="编辑优先级" value={draft.severity} onChange={e=>c.setDraft({...draft,severity:e.target.value as typeof draft.severity})}>{['一般','重要','紧急'].map(v=><option key={v}>{v}</option>)}</select></label></div>{draft.category==='其他'&&<label>自定义关注类型（选填）<input maxLength={30} value={draft.customCategory||''} onChange={e=>c.setDraft({...draft,customCategory:e.target.value})}/></label>}<label>最近确认日期（选填）<input type="date" value={draft.reviewedAt||''} onChange={e=>c.setDraft({...draft,reviewedAt:e.target.value})}/></label><label>行动摘要（选填）<input aria-label="行动摘要" maxLength={40} value={draft.summary||''} onChange={e=>c.setDraft({...draft,summary:e.target.value})}/></label><label>老师需要做什么（选填）<textarea maxLength={180} value={draft.instruction} onChange={e=>c.setDraft({...draft,instruction:e.target.value})}/></label><label>需避免或注意的情况（选填）<textarea maxLength={180} value={draft.contraindication||''} onChange={e=>c.setDraft({...draft,contraindication:e.target.value})}/></label><fieldset><legend>适用场景（选填）</legend><div className={s.checks}>{contexts.map(v=><label key={v}><input type="checkbox" checked={draft.actionContexts?.includes(v)||false} onChange={()=>c.setDraft({...draft,actionContexts:draft.actionContexts?.includes(v)?draft.actionContexts.filter(x=>x!==v):[...(draft.actionContexts??[]),v]})}/>{v}</label>)}</div><label>自定义场景（顿号或逗号分隔）<input maxLength={80} aria-label="自定义场景" value={c.customContextsText} onChange={e=>c.setCustomContextsText(e.target.value)}/></label></fieldset><p>学生名单中的主要监护人：{contact(draft.studentId)}</p></fieldset>{c.error&&<p role="alert" className={s.error}>{c.error}</p>}{c.pending&&<p>改动已在本机待同步。请重试同步，或导出草稿后再载入最新数据。</p>}{c.conflict&&<div className={s.recovery}><button onClick={c.exportDraft}>导出草稿</button><button onClick={()=>setReplace(true)}>载入最新数据</button></div>}</Dialog>}
 {picker&&draft&&<StudentLookupDialog title="选择照护学生" subtitle="按姓名或学号查找；支持大班额。" students={c.students} selectedId={draft.studentId} onPick={v=>c.setDraft({...draft,studentId:v.id})} onClose={()=>setPicker(false)}/>}
 <Dialog open={c.confirmClose} title={c.pending?'还有待同步改动':'放弃未保存改动？'} onRequestClose={()=>c.setConfirmClose(false)} footer={<><button onClick={()=>c.setConfirmClose(false)}>继续编辑</button>{!c.pending&&<button onClick={c.discard}>放弃改动</button>}</>}><p>{c.pending?'关闭不会撤销已在本机的改动，请返回编辑器重试同步。':'放弃后将不保留这次输入。'}</p></Dialog>
 <Dialog open={c.confirmDelete} title="确认删除照护登记" onRequestClose={()=>{c.setConfirmDelete(false);c.requestClose();}} footer={<><button onClick={()=>{c.setConfirmDelete(false);c.requestClose();}}>取消删除</button><button className={s.danger} disabled={c.busy||c.readOnly} onClick={()=>void c.persist('delete')}>确认删除</button></>}><p>这条登记会从当前班级移除，且无法恢复。</p></Dialog>
 <Dialog open={replace} title="载入最新数据？" onRequestClose={()=>setReplace(false)} footer={<><button onClick={()=>setReplace(false)}>保留本机草稿</button><button onClick={c.loadLatest}>确认载入最新</button></>}><p>这会替换本机待同步改动。请先导出需要保留的草稿。</p></Dialog></ThemeBoundary>
 </section>;
}
