import {useState} from 'react';
import {Dialog} from '@/app/components/workbench/ui/Dialog';
import {ThemeBoundary} from '@/app/components/workbench/theme/ThemeBoundary';
import {CampusIcon} from '@/app/components/campus/primitives';
import type {useGrowthDesignController} from './useGrowthDesignController';
import type {GrowthTimelineItem} from './read-model';
import art from './archive-p01.png';
import s from './GrowthDesign.module.css';
type Controller=ReturnType<typeof useGrowthDesignController>;
export function GrowthDesign({controller:c}:{controller:Controller}){
 const [filtersOpen,setFiltersOpen]=useState(false),[entry,setEntry]=useState<GrowthTimelineItem|null>(null),[replaceOpen,setReplaceOpen]=useState(false);
 const m=c.m;
 const filter=(label:string,key:keyof Controller['filters'],options:string[])=><label>{label}<select aria-label={label} value={c.filters[key]} onChange={e=>c.changeFilter(key,e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select></label>;
 const rosterFilters=<div className={s.filters}>{filter('小组','groupFilter',['全部小组',...(m?.groupOptions.map(String)??[])])}{filter('状态','studentStatusFilter',['全部状态','需要跟进','表现良好','整体稳定'])}{filter('记录覆盖','coverageFilter',['全部记录','有记录','暂无记录'])}{filter('排序','studentSort',['默认排序','记录多优先','积分低优先','成绩低优先'])}<button onClick={c.reset}>重置筛选</button><small>状态、成绩及积分排序沿用已有规则，不能作为学生的长期评价。</small></div>;
 return <section className={s.page} data-growth-design="page" data-mobile={c.mobile||undefined}>
  {(!c.mobile||!c.detailOpen)&&<header className={s.heading}><div><h1>成长档案</h1><p>{c.data.rosterClasses?.[0]?.name} · 记录具体事实，留下成长足迹。</p><span>{c.data.students.length}名学生 · {m?.studentsWithEvidence??0}人已有记录</span></div><img src={typeof art==='string'?art:art.src} alt="" width="1536" height="1024"/></header>}
  {c.message&&<p className={s.message} role="status">{c.message}<button aria-label="关闭提示" onClick={()=>c.setMessage('')}>关闭</button></p>}
  <div className={s.layout}>
   {(!c.mobile||!c.detailOpen)&&<aside className={s.directory} aria-label="学生目录">
    <div className={s.searchRow}><label><CampusIcon name="search"/><input aria-label="搜索学生" placeholder="姓名或学号" value={c.filters.keyword} onChange={e=>c.changeFilter('keyword',e.target.value)}/></label><button aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(!filtersOpen)}>筛选</button></div>
    {filtersOpen&&rosterFilters}
    <div className={s.quick}><button aria-pressed={c.filters.studentStatusFilter==='全部状态'&&c.filters.coverageFilter==='全部记录'} onClick={c.reset}>全部 {c.data.students.length}</button><button aria-pressed={c.filters.studentStatusFilter==='需要跟进'} onClick={()=>{c.changeFilter('studentStatusFilter','需要跟进');c.changeFilter('coverageFilter','全部记录');}}>需跟进 {m?.attentionCount??0}</button><button aria-pressed={c.filters.coverageFilter==='暂无记录'} onClick={()=>{c.changeFilter('coverageFilter','暂无记录');c.changeFilter('studentStatusFilter','全部状态');}}>暂无记录 {m?.noEvidenceCount??0}</button></div>
    <h2>学生目录 <small>{m?.shownStudents.length??0}人</small></h2>
    <div className={s.students}>{c.pageStudents.map(student=><button key={student.id} data-student-id={student.id} className={s.student} aria-pressed={student.id===c.id} onClick={()=>c.selectStudent(student.id)}><span className={s.avatar} aria-hidden="true">{student.name.slice(0,1)}</span><span className={s.name}><b>{student.name}</b><small>学号{student.studentNo||'未填'} · 第{student.group}组</small></span><span className={s.count}>{m?.studentEvidenceCount(student)}条记录 <CampusIcon name="chevron"/></span></button>)}</div>
    {!c.pageStudents.length&&<div className={s.empty}><h3>{c.data.students.length?'没有匹配的学生':'先建立学生名单'}</h3><p>{c.data.students.length?'换一个姓名或筛选条件试试。':'建立名单后即可归集成长记录。'}</p>{c.data.students.length>0&&<button onClick={c.reset}>清除搜索和筛选</button>}</div>}
    <nav className={s.pagination} aria-label="学生分页"><button disabled={c.safeListPage===1} onClick={()=>c.setListPage(p=>p-1)}>上一页</button><span>{c.safeListPage}/{c.listPages}</span><button disabled={c.safeListPage===c.listPages} onClick={()=>c.setListPage(p=>p+1)}>下一页</button></nav>
   </aside>}
   {m&&(!c.mobile||c.detailOpen)&&<main className={s.archive}>
    {c.mobile&&<button className={s.back} onClick={()=>c.setDetailOpen(false)}>返回学生列表</button>}
    <header className={s.identity}><span className={s.portrait} aria-hidden="true">{m.student.name.slice(0,1)}</span><div><h2>{m.student.name}</h2><p>学号{m.student.studentNo||'未填'} · 第{m.student.group}组</p>{m.cadre&&<small>{m.cadre.role}</small>}</div><div className={s.commands}><button className={s.primary} disabled={c.readOnly||c.busy} onClick={c.openComposer}>添加记录</button><button onClick={()=>c.setSummaryOpen(true)}>查看摘要</button></div></header>
    <div className={s.timelineHead}><h2>成长事实 <small>{m.filteredEvidence.length}条</small></h2><div className={s.timeFilters}>{filter('时间范围','range',['全部时间','近7天','近30天','本学期'])}{filter('来源类型','kind',['全部类型','老师补充','沟通记录','积分表现','作业记录'])}</div></div>
    <div className={s.timeline}>{m.visibleEvidence.map(item=><article key={item.id} className={s.event} data-kind={item.kind}><time>{item.date}</time><div className={s.eventBody}><span className={s.source}>{item.kind} · {item.label}</span><h3>{item.title}</h3><p>{item.content}</p>{item.followUp&&<p className={s.follow}>后续观察：{item.followUp}</p>}<button className={s.textAction} onClick={()=>setEntry(item)}>查看全文</button></div></article>)}</div>
    {!m.visibleEvidence.length&&<div className={s.empty}><h3>{m.evidence.length?'当前条件下没有记录':'还没有成长记录'}</h3><p>{m.evidence.length?'调整时间或来源条件，查看其他事实。':'记录一次具体观察，开始积累成长事实。'}</p><button onClick={()=>{c.changeFilter('range','全部时间');c.changeFilter('kind','全部类型');}}>重置时间与来源</button></div>}
    <nav className={s.pagination} aria-label="成长记录分页"><button disabled={m.safePage===1} onClick={()=>c.changeFilter('page',m.safePage-1)}>上一页</button><span>第{m.safePage}/{m.pageCount}页</span><button disabled={m.safePage===m.pageCount} onClick={()=>c.changeFilter('page',m.safePage+1)}>下一页</button></nav>
   </main>}
  </div>
  <ThemeBoundary>
   <Dialog open={c.composer} title={`添加成长记录 · ${m?.student.name??''}`} onRequestClose={c.requestClose} busy={c.busy}><form className={s.editor} onSubmit={e=>{e.preventDefault();void c.saveEvidence();}}><p>记录具体事实，不写空泛评价。</p><div className={s.fieldPair}><label>日期<input aria-label="记录日期" type="date" disabled={c.busy||c.pending} value={c.draft.date} onChange={e=>c.setDraft(d=>({...d,date:e.target.value}))}/></label><label>类型<select aria-label="记录类型" disabled={c.busy||c.pending} value={c.draft.type} onChange={e=>c.setDraft(d=>({...d,type:e.target.value}))}>{['学习','活动','荣誉','日常','进步','表扬记录'].map(v=><option key={v}>{v}</option>)}</select></label></div><label>标题<input aria-label="记录标题" maxLength={40} disabled={c.busy||c.pending} value={c.draft.title} onChange={e=>c.setDraft(d=>({...d,title:e.target.value}))}/><small>{c.draft.title.length}/40</small></label><label>具体事实<textarea aria-label="具体事实" maxLength={500} rows={5} disabled={c.busy||c.pending} value={c.draft.content} onChange={e=>c.setDraft(d=>({...d,content:e.target.value}))}/><small>{c.draft.content.length}/500</small></label><label>后续观察点<textarea aria-label="后续观察点" maxLength={300} rows={3} disabled={c.busy||c.pending} value={c.draft.followUp} onChange={e=>c.setDraft(d=>({...d,followUp:e.target.value}))}/><small>{c.draft.followUp?.length??0}/300</small></label>{c.error&&<p role="alert" className={s.error}>{c.error}</p>}{c.conflict&&<section className={s.recovery} aria-label="冲突恢复"><p>工作区版本已变化。先导出本机草稿，再选择是否载入最新版本。</p><button type="button" onClick={c.exportDraft}>导出当前草稿</button><button type="button" onClick={()=>setReplaceOpen(true)}>载入最新版本</button></section>}<footer><button type="button" disabled={c.busy} onClick={c.requestClose}>取消</button><button className={s.primary} type="submit" disabled={c.readOnly||c.busy}>{c.busy?'保存中…':c.pending?'重试同步':'保存成长记录'}</button></footer></form></Dialog>
   <Dialog open={replaceOpen} title="载入最新版本前确认" onRequestClose={()=>setReplaceOpen(false)}><div className={s.editor}><p>此操作将替换本机未同步内容。需要保留时，请先导出当前草稿。</p><footer><button onClick={()=>setReplaceOpen(false)}>返回保留草稿</button><button onClick={c.loadLatest}>确认载入最新版本</button></footer></div></Dialog>
   <Dialog open={c.confirmClose} title="当前记录尚未保存" onRequestClose={()=>c.setConfirmClose(false)}><div className={s.editor}><p>{c.pending?'记录已在本机待同步，请先重试保存。':'离开会丢弃本次尚未保存的输入。'}</p><footer><button onClick={()=>c.setConfirmClose(false)}>继续编辑</button>{!c.pending&&<button onClick={c.discard}>放弃本次输入</button>}</footer></div></Dialog>
   <Dialog open={c.summaryOpen} title={`${m?.student.name??''} · 已有摘要`} onRequestClose={()=>c.setSummaryOpen(false)}><div className={s.editor}><p className={s.summaryWarning}>以下沿用旧规则生成，成绩与作业值没有明确长期统计范围，不能作为学生的常态评价。摘要口径待重新设计。</p><p>{m?.summary}</p><h3>旧规则优势观察</h3>{m?.strengths.map(v=><p key={v}>{v}</p>)}<h3>旧规则跟进建议</h3>{m?.followUps.map(v=><p key={v}>{v}</p>)}<footer><button onClick={()=>void c.copySummary()}>复制摘要</button><button onClick={()=>window.print()}>打印素材</button></footer>{c.message&&<p role="status">{c.message}</p>}</div></Dialog>
   <Dialog open={!!entry} title={entry?.title??'成长事实'} onRequestClose={()=>setEntry(null)}><div className={s.editor}><p>{entry?.date} · {entry?.kind} · {entry?.label}</p><p>{entry?.content}</p>{entry?.followUp&&<p>后续观察：{entry.followUp}</p>}</div></Dialog>
  </ThemeBoundary>
 </section>;
}
