import type {ExamReflection} from '@/lib/classroom';
import {useState} from 'react';
import {ThemeBoundary} from '@/app/components/workbench/theme/ThemeBoundary';
import {Dialog} from '@/app/components/workbench/ui/Dialog';
import type {ExamReflectionDraft} from '@/app/w/[token]/features/reflections/operations';
import type {useReflectionDesignController} from './useReflectionDesignController';
import art from './notebook-p01.png';
import {SavedReflectionLibrary,SavedReflectionDetail} from './SavedReflectionViews';
import s from './ReflectionDesign.module.css';
type C=ReturnType<typeof useReflectionDesignController>;
export function ReflectionDesign({controller:c}:{controller:C}){
 const [legacy,setLegacy]=useState<ExamReflection|null>(null),[legacyExam,setLegacyExam]=useState('');
 const [library,setLibrary]=useState(false),[examQuery,setExamQuery]=useState(''),[subject,setSubject]=useState('全部科目'),[year,setYear]=useState('全部年份'),[month,setMonth]=useState('全部月份'),[sort,setSort]=useState('新到旧'),[examPage,setExamPage]=useState(1),[scores,setScores]=useState(false),[replace,setReplace]=useState(false);
 const filtered=c.exams.filter(e=>`${e.title} ${e.date} ${e.subjects.join(' ')}`.includes(examQuery.trim())&&(subject==='全部科目'||e.subjects.includes(subject))&&(year==='全部年份'||e.date.startsWith(year))&&(month==='全部月份'||e.date.slice(5,7)===month)).sort((a,b)=>sort==='新到旧'?b.date.localeCompare(a.date):a.date.localeCompare(b.date)),examPages=Math.max(1,Math.ceil(filtered.length/10)),safeExamPage=Math.min(examPage,examPages);
 const isEditor=!c.mobile||c.editorOpen,selectedVisible=c.rows.some(r=>r.student.id===c.studentId),showEditor=isEditor&&!!c.student&&!!c.exam&&(c.mobile||selectedVisible);
 const recovery=<>{c.error&&<p className={s.error} role="alert">{c.error}</p>}{c.pending&&!c.busy&&<div className={s.recovery}><span>本机反思尚未同步</span><button onClick={()=>void c.sync()}>重试同步</button>{c.conflict&&<><button onClick={c.exportDraft}>导出草稿</button><button onClick={()=>setReplace(true)}>载入最新数据</button></>}</div>}</>;
 const field=(label:string,key:keyof ExamReflectionDraft,required=false)=><label className={key==='action'?s.actionField:undefined}><span>{label}{required&&<b className={s.required}> *</b>}{['familyMessage','teacherNote'].includes(key)&&<small>（选填）</small>}</span><textarea aria-label={label} aria-required={required} disabled={c.locked} value={c.draft[key]??''} onChange={e=>c.setField(key,e.target.value)} rows={2}/></label>;
 const editSaved=(r:ExamReflection)=>{if(r.examId)c.chooseReflection(r);else{setLegacy(r);setLegacyExam('');}};
 const saveEditor=async(status:ExamReflection['status'])=>{if(await c.submit(status))c.finishSavedEdit();};
 const editor=<section className={s.editor} aria-label="反思填写">
  {(c.mobile||c.tab==='saved')&&<nav className={s.back}><button onClick={c.back}>{c.tab==='saved'?'返回反思详情':'返回学生列表'}</button><span>{c.pending?'待同步':c.dirty?'未保存':c.existing?.status??'未填写'}</span></nav>}
  <header className={s.studentContext}><div><h2>{c.student?.name}</h2><span>学号{c.student?.studentNo}</span><span className={s.badge} data-status={c.existing?.status}>{c.pending?'待同步':c.dirty?'未保存':c.existing?.status??'未填写'}</span></div><label>日期<input type="date" aria-label="反思日期" disabled={c.locked} value={c.draft.date} onChange={e=>c.setField('date',e.target.value)}/></label>{c.mobile&&<p>{c.exam?.title} · {c.exam?.date}</p>}</header>
  <div className={s.scoreContext}><span>本次考试</span>{!c.mobile&&c.exam?.subjects.map(sub=><span key={sub}>{sub} {c.exam?.scores[c.studentId]?.[sub]??'未录'}/{c.exam?.subjectMaxScores?.[sub]??100}</span>)}<button onClick={()=>setScores(true)}>查看本次成绩</button></div>
  {c.readOnly&&<p className={s.readonly}>当前为只读模式，可查看和复制反思。</p>}
  {recovery}
  <form onSubmit={e=>{e.preventDefault();void saveEditor('草稿');}} className={s.form}>
   {field('主要问题','problem',true)}{field('原因分析','reason')}{field('下一步行动','action')}
   <div className={s.optional}>{field('写给家长的话','familyMessage')}{field('班主任跟进','teacherNote')}</div>
   <footer className={s.actions}><div><button type="submit" disabled={c.locked}>{c.busy?'保存中…':'保存草稿'}</button><button type="button" className={s.primary} disabled={c.locked} onClick={()=>void saveEditor('已完成')}>完成并归档</button>{c.existing&&<button type="button" className={s.textButton} onClick={()=>void c.copy()}>复制反思</button>}<span role="status">{c.saved?'已保存':c.pending?'待同步':c.dirty?'未保存':''}</span></div><p>归档到校内沟通记录，不自动发送给家长。</p></footer>
  </form>
 </section>;
 return <ThemeBoundary className={s.page}>
  {!(c.mobile&&c.editorOpen)&&!(c.tab==='saved'&&c.savedView!=='library')&&<><header className={s.heading}><div><h1>{c.tab==='saved'&&c.mobile?'已保存反思':'考试反思'}</h1><p>{c.tab==='saved'?'回看每一次复盘，找到后续行动。':'把问题写清，把下一步约定下来。'}</p></div><img src={typeof art==='string'?art:art.src} width={220} height={140} alt=""/></header>{c.tab==='students'&&c.exam&&<section className={s.examBand}><div><h2>当前考试 · {c.exam.title}</h2><p>{c.exam.date} · {c.exam.subjects.join(' / ')}</p></div><button onClick={()=>setLibrary(true)}>切换考试</button></section>}</>}
  {c.tab==='saved'?c.savedView==='library'?<SavedReflectionLibrary c={c} onEdit={editSaved}/>:c.savedView==='detail'?<SavedReflectionDetail c={c} onEdit={editSaved}/>:<div className={s.savedEditor+' '+s.workspace} data-editor={c.mobile}>{editor}</div>:!c.exams.length?<section className={s.empty}><h2>还没有考试记录</h2><p>先在成绩分析中建立一次考试，再填写对应反思。</p><p>此独立预览仅使用合成数据，可在左下角切换“normal”查看完整设计。</p></section>:!c.students.length?<section className={s.empty}><h2>当前班级暂无学生</h2><p>添加学生后，可逐人填写本次考试反思。</p></section>:<div className={s.workspace} data-editor={c.mobile&&c.editorOpen}>
   {!(c.mobile&&c.editorOpen)&&<aside className={s.queue} aria-label="学生复盘状态"><h2>学生复盘状态</h2><p className={c.tab==='saved'?s.libraryScope:undefined}>{c.tab==='saved'?'本班全部考试记录':`本次考试 · ${c.students.length}名学生`}</p><nav className={s.tabs}><button aria-pressed={c.tab==='students'} onClick={()=>c.switchTab('students')}>学生状态 {c.students.length}</button><button aria-pressed={c.tab==='saved'} onClick={()=>c.switchTab('saved')}>已保存反思 {c.reflections.length}</button></nav><label className={s.search}><span className={s.searchIcon} aria-hidden="true"/><input aria-label="搜索学生或反思" placeholder="搜索姓名、学号或反思内容" value={c.query} onChange={e=>c.setQuery(e.target.value)}/></label><div className={s.filters}><select aria-label="反思状态" value={c.status} onChange={e=>c.setStatus(e.target.value)}>{['全部状态','未填写','草稿','已完成'].map(v=><option key={v}>{v}</option>)}</select><label><input type="checkbox" checked={c.focusOnly} onChange={e=>c.setFocusOnly(e.target.checked)}/>仅看重点跟进</label></div>
   {!showEditor&&recovery}{!c.rows.length&&<div className={s.empty}><h3>{c.tab==='saved'?'没有符合条件的已保存反思':'没有找到学生'}</h3><p>试试更换关键词或筛选条件。</p><button onClick={()=>{c.setQuery('');c.setStatus('全部状态');c.setFocusOnly(false);}}>重置筛选</button></div>}
   <div className={s.rows}>{c.visible.map(row=><button key={row.reflection?.id??row.student.id} className={s.row} aria-current={(c.tab==='saved'?row.reflection?.id===c.draft.id:row.student.id===c.studentId)?'true':undefined} onClick={()=>{if(c.tab==='saved'&&row.reflection){if(row.reflection.examId)c.chooseReflection(row.reflection);else{setLegacy(row.reflection);setLegacyExam('');}}else c.chooseStudent(row.student.id);}}><span><strong>{row.student.name}</strong><small>学号{row.student.studentNo}</small>{c.tab==='saved'&&<small>{c.exams.find(e=>e.id===row.reflection?.examId)?.title??'未关联考试'} · {row.reflection?.date}</small>}{row.focus&&<em>重点跟进</em>}</span><span><b className={s.badge} data-status={row.reflection?.status}>{row.reflection?.status??'未填写'}</b>{c.mobile&&<small>{row.reflection?.status==='已完成'?'查看反思':row.reflection?'继续填写':'填写'}</small>}</span></button>)}</div><nav className={s.pagination} aria-label="学生分页"><button disabled={c.safePage===1} onClick={()=>c.setPage(c.safePage-1)}>上一页</button><span>{c.safePage} / {c.pages} · {c.rows.length}{c.tab==='saved'?'条':'人'}</span><button disabled={c.safePage===c.pages} onClick={()=>c.setPage(c.safePage+1)}>下一页</button></nav></aside>}
   {showEditor?editor:!c.mobile&&<div className={s.empty}><h2>选择一名学生开始复盘</h2><p>当前筛选不包含原来正在查看的学生。</p>{c.dirty&&<><p>未保存的编辑仍保留，可清除筛选返回。</p><button onClick={()=>{c.setQuery('');c.setStatus('全部状态');c.setFocusOnly(false);}}>返回当前反思</button></>}</div>}
  </div>}
  {c.message&&<p className={s.toast} role="status">{c.message}</p>}
  <Dialog open={library} title="选择考试" onRequestClose={()=>setLibrary(false)}><div className={s.library}><input aria-label="搜索考试" placeholder="搜索考试、日期或科目" value={examQuery} onChange={e=>{setExamQuery(e.target.value);setExamPage(1);}}/><div className={s.examFilters}><label>科目<select value={subject} onChange={e=>{setSubject(e.target.value);setExamPage(1);}}>{['全部科目',...new Set(c.exams.flatMap(e=>e.subjects))].map(v=><option key={v}>{v}</option>)}</select></label><label>年份<select value={year} onChange={e=>{setYear(e.target.value);setExamPage(1);}}>{['全部年份',...new Set(c.exams.map(e=>e.date.slice(0,4)))].map(v=><option key={v}>{v}</option>)}</select></label><label>月份<select value={month} onChange={e=>{setMonth(e.target.value);setExamPage(1);}}>{['全部月份',...Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0'))].map(v=><option key={v}>{v}</option>)}</select></label><label>排序<select value={sort} onChange={e=>setSort(e.target.value)}><option>新到旧</option><option>旧到新</option></select></label></div>{filtered.slice((safeExamPage-1)*10,safeExamPage*10).map(e=><button className={s.examRow} key={e.id} onClick={()=>c.chooseExam(e.id,()=>setLibrary(false))}><strong>{e.title}</strong><span>{e.date} · {e.subjects.join(' / ')}</span><span>{e.id===c.examId?'当前考试':'选择'}</span></button>)}{!filtered.length&&<p>没有找到符合条件的考试。</p>}<nav className={s.pagination}><button disabled={safeExamPage===1} onClick={()=>setExamPage(safeExamPage-1)}>上一页</button><span>{safeExamPage}/{examPages}</span><button disabled={safeExamPage===examPages} onClick={()=>setExamPage(safeExamPage+1)}>下一页</button></nav></div></Dialog>
  <Dialog open={!!legacy} title="未关联考试的历史反思" onRequestClose={()=>setLegacy(null)} footer={<><button onClick={()=>legacy&&void c.copy(legacy)}>复制反思</button><button disabled={c.locked||!legacyExam} onClick={()=>legacy&&c.chooseReflection(legacy,legacyExam,()=>setLegacy(null))}>关联所选考试并编辑</button></>}>{legacy&&<div className={s.legacy}><p>{c.students.find(st=>st.id===legacy.studentId)?.name} · {legacy.date} · {legacy.status}</p>{[['主要问题',legacy.problem],['原因分析',legacy.reason],['下一步行动',legacy.action],['写给家长',legacy.familyMessage],['班主任跟进',legacy.teacherNote]].map(([label,value])=><section key={label}><h3>{label}</h3><p>{value||'未填写'}</p></section>)}<label>关联考试<select aria-label="关联考试" disabled={c.locked} value={legacyExam} onChange={e=>setLegacyExam(e.target.value)}><option value="">选择一场考试</option>{c.exams.filter(e=>!c.reflections.some(r=>r.id!==legacy.id&&r.studentId===legacy.studentId&&r.examId===e.id)).map(e=><option key={e.id} value={e.id}>{e.title} · {e.date}</option>)}</select></label><p>保存后才确认关联，保留这条历史反思的原记录编号。</p>{c.error&&<p role="alert" className={s.error}>{c.error}</p>}</div>}</Dialog>
  <Dialog open={scores} title={`${c.student?.name??''} · 本次成绩`} onRequestClose={()=>setScores(false)}><div className={s.scoreDetails}><p>{c.exam?.title} · {c.exam?.date}</p>{c.exam?.subjects.map(sub=><p key={sub}><span>{sub}</span><strong>{c.exam?.scores[c.studentId]?.[sub]??'未录入'} / {c.exam?.subjectMaxScores?.[sub]??100}</strong></p>)}<small>空白不等于零分；这些分数只对应本次考试。</small></div></Dialog>
  <Dialog open={c.confirm} title="有未保存的反思" onRequestClose={()=>c.setConfirm(false)} footer={<><button onClick={()=>c.setConfirm(false)}>继续填写</button><button onClick={c.discard}>放弃修改并继续</button></>}><p>切换后会丢弃尚未保存的输入，已保存记录保持不变。</p></Dialog>
  <Dialog open={replace} title="载入最新数据" onRequestClose={()=>setReplace(false)} footer={<><button onClick={c.exportDraft}>先导出本机草稿</button><button onClick={c.loadLatest}>确认替换本机内容</button></>}><p>载入最新数据会替换当前本机待同步反思，请先导出需要保留的内容。</p></Dialog>
 </ThemeBoundary>;
}
