import {useEffect,useRef,useState} from 'react';
import {makeId,type ClassroomData,type ExamReflection} from '@/lib/classroom';
import {copyTextToClipboard} from '@/lib/clipboard';
import {examReflectionsForClass,localReflectionDate,saveExamReflection,type ExamReflectionDraft} from '@/app/w/[token]/features/reflections/operations';
type Props={data:ClassroomData;update:(fn:(d:ClassroomData)=>ClassroomData)=>void;save:()=>Promise<boolean>;readOnly:boolean;mobile:boolean;conflict:boolean;exportDraft:()=>void;loadLatest:()=>void};
const blank=(studentId:string,examId:string):ExamReflectionDraft=>({studentId,examId,date:localReflectionDate(),problem:'',reason:'',action:'',familyMessage:'',teacherNote:''});
export function useReflectionDesignController(p:Props){
 const {data,update,save,readOnly,mobile}=p,classId=data.activeClassId??'class-1';
 const students=data.rosterClasses?.find(x=>x.id===classId)?.students??data.students,exams=(data.scoreExams??[]).filter(x=>!x.classId||x.classId===classId),reflections=examReflectionsForClass(data,classId);
 const [examId,setExamId]=useState(exams[0]?.id??''),[studentId,setStudentId]=useState(students[0]?.id??''),[draft,setDraft]=useState<ExamReflectionDraft>(()=>reflections.find(r=>r.examId===exams[0]?.id&&r.studentId===students[0]?.id)??blank(students[0]?.id??'',exams[0]?.id??''));
 const [baseline,setBaseline]=useState(JSON.stringify(draft)); const pendingRef=useRef<ExamReflection|null>(null),busyRef=useRef(false),actionRef=useRef<(()=>void)|null>(null);
 const [savedView,setSavedView]=useState<'library'|'detail'|'edit'>('library'),[savedId,setSavedId]=useState(''),[libraryExam,setLibraryExam]=useState('all');
 const savedReflection=reflections.find(r=>r.id===savedId);
 const [busy,setBusy]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[confirm,setConfirm]=useState(false),[editorOpen,setEditorOpen]=useState(false),[tab,setTab]=useState('students'),[query,setQuery]=useState(''),[status,setStatus]=useState('全部状态'),[focusOnly,setFocusOnly]=useState(false),[page,setPage]=useState(1),[message,setMessage]=useState('');
 const exam=exams.find(e=>e.id===examId),student=students.find(s=>s.id===studentId),existing=reflections.find(r=>r.id===draft.id)??reflections.find(r=>r.examId===examId&&r.studentId===studentId),dirty=JSON.stringify(draft)!==baseline,locked=readOnly||busy||pending;
 const current=reflections.filter(r=>r.examId===examId),allRows=tab==='saved'?reflections.map(r=>({student:students.find(st=>st.id===r.studentId)!,reflection:r,focus:!!exams.find(e=>e.id===r.examId)?.followUpStudentIds?.includes(r.studentId)})):students.map(st=>({student:st,reflection:current.find(r=>r.studentId===st.id),focus:!!exam?.followUpStudentIds?.includes(st.id)}));
 const rows=allRows.filter(row=>(tab!=='saved'||libraryExam==='all'||(libraryExam==='unlinked'?!row.reflection?.examId:row.reflection?.examId===libraryExam))&&(!focusOnly||row.focus)&&(status==='全部状态'||(row.reflection?.status??'未填写')===status)&&(`${row.student.name} ${row.student.studentNo} ${row.reflection?.date??''} ${exams.find(e=>e.id===row.reflection?.examId)?.title??'未关联'} ${row.reflection?.problem??''} ${row.reflection?.reason??''} ${row.reflection?.action??''} ${row.reflection?.familyMessage??''} ${row.reflection?.teacherNote??''}`).includes(query.trim()));
 if(tab==='saved')rows.sort((a,b)=>(b.reflection?.date??'').localeCompare(a.reflection?.date??'')||(a.student.studentNo??a.student.name).localeCompare(b.student.studentNo??b.student.name));
 const pageSize=tab==='saved'?(mobile?3:6):(mobile?8:10),pages=Math.max(1,Math.ceil(rows.length/pageSize)),safePage=Math.min(page,pages),visible=rows.slice((safePage-1)*pageSize,safePage*pageSize);
 useEffect(()=>{setPage(1);},[query,status,focusOnly,tab,libraryExam]);
 useEffect(()=>{if(!message)return;const id=setTimeout(()=>setMessage(''),2500);return()=>clearTimeout(id);},[message]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty||pendingRef.current||busyRef.current){e.preventDefault();e.returnValue='';}};const nav=(e:Event)=>{if(dirty||pendingRef.current||busyRef.current){e.preventDefault();setError('请先保存或处理当前反思，再离开页面。');}};window.addEventListener('beforeunload',before);window.addEventListener('classroom:before-navigate',nav);return()=>{window.removeEventListener('beforeunload',before);window.removeEventListener('classroom:before-navigate',nav);};},[dirty]);
 function guard(action:()=>void){if(busyRef.current||pendingRef.current){setError('请先完成当前保存或重试同步。');return;}if(dirty){actionRef.current=action;setConfirm(true);}else action();}
 function load(stId:string,exId:string){const next=reflections.find(r=>r.studentId===stId&&r.examId===exId)??blank(stId,exId);setStudentId(stId);setExamId(exId);setDraft(next);setBaseline(JSON.stringify(next));setSaved(false);setError('');}
 function chooseStudent(id:string){guard(()=>{load(id,examId);setEditorOpen(true);});}
 function chooseReflection(r:ExamReflection,bindExamId?:string,done?:()=>void){guard(()=>{const target=r.examId??bindExamId;if(!target){setError('请先选择需要关联的考试。');return;}if(reflections.some(other=>other.id!==r.id&&other.studentId===r.studentId&&other.examId===target)){setError('该学生在这次考试已有反思，请选择另一场考试，避免重复记录。');return;}setStudentId(r.studentId);setExamId(target);setDraft({...r,examId:target});setBaseline(JSON.stringify(r));setSavedId(r.id);if(tab==='saved')setSavedView('edit');setSaved(false);setError('');setEditorOpen(true);done?.();});}
 function viewReflection(r:ExamReflection){guard(()=>{setSavedId(r.id);setSavedView('detail');setEditorOpen(false);setError('');});}
 function finishSavedEdit(){if(tab==='saved'){setSavedView('detail');setEditorOpen(false);}}
 function backToLibrary(){guard(()=>{setSavedView('library');setEditorOpen(false);setError('');});}
 function chooseExam(id:string,done:()=>void){guard(()=>{load(students[0]?.id??'',id);setEditorOpen(false);setQuery('');setStatus('全部状态');setFocusOnly(false);setPage(1);done();});}
 function switchTab(next:string){guard(()=>{setTab(next);setSavedView('library');setEditorOpen(false);setQuery('');setStatus('全部状态');setFocusOnly(false);});}
 function back(){guard(()=>{setEditorOpen(false);if(tab==='saved')setSavedView('detail');});}
 function discard(){const action=actionRef.current;actionRef.current=null;setConfirm(false);setDraft(JSON.parse(baseline));action?.();}
 function setField(key:keyof ExamReflectionDraft,value:string){if(locked)return;setDraft(d=>({...d,[key]:value}));setSaved(false);setError('');}
 async function sync(){if(readOnly||busyRef.current||!pendingRef.current)return false;busyRef.current=true;setBusy(true);setError('');try{if(!await save()){setError('同步失败，反思仍在本机。请重试，不会重复归档。');return false;}setBaseline(JSON.stringify(pendingRef.current));setDraft(pendingRef.current);pendingRef.current=null;setPending(false);setSaved(true);return true;}catch{setError('连接中断，反思仍在本机，请重试同步。');return false;}finally{busyRef.current=false;setBusy(false);}}
 async function submit(nextStatus:ExamReflection['status']){if(locked||!student||!exam)return false;const id=draft.id??makeId('reflection'),recordId=makeId('reflection-record'),result=saveExamReflection(data,classId,{...draft,id},nextStatus,()=>id,()=>recordId);if(!result.reflection){setError(result.error);return false;}pendingRef.current=result.reflection;setPending(true);setDraft(result.reflection);update(currentData=>{const applied=saveExamReflection(currentData,classId,{...draft,id},nextStatus,()=>id,()=>recordId);return applied.data??currentData;});return sync();}
 async function copy(value:ExamReflectionDraft=draft){const ok=await copyTextToClipboard([students.find(st=>st.id===value.studentId)?.name,exams.find(e=>e.id===value.examId)?.title??'未关联考试',`主要问题：${value.problem}`,`原因分析：${value.reason}`,`下一步行动：${value.action}`,`写给家长：${value.familyMessage}`,`班主任跟进：${value.teacherNote}`].join('\n'),'已复制反思');if(ok)setMessage('已复制反思');else setError('复制失败，请手动选择反思内容或重试。');}
 return {...p,students,exams,reflections,exam,student,draft,existing,current,rows,visible,pages,safePage,pageSize,examId,studentId,busy,pending,error,saved,confirm,editorOpen,tab,query,status,focusOnly,dirty,locked,message,setMessage,setField,setQuery,setStatus,setFocusOnly,setPage,setError,setConfirm,chooseStudent,chooseReflection,chooseExam,switchTab,back,discard,submit,sync,copy,guard,savedView,savedReflection,libraryExam,setLibraryExam,viewReflection,finishSavedEdit,backToLibrary};
}
