"use client";
import { copyTextToClipboard } from "@/lib/clipboard";
import { useMemo, useState } from "react";
import { makeId } from "@/lib/classroom";
import type { ClassroomData } from "@/lib/classroom";
import { WorkbenchPageHeader } from "./WorkbenchPageHeader";
const today = () => new Date().toISOString().slice(0, 10);
export function ClassroomTools({ data, update }: { data: ClassroomData; update: (fn: (d: ClassroomData) => ClassroomData) => void }) {
  const classId = data.activeClassId ?? data.rosterClasses?.[0]?.id ?? ""; const students = data.students;
  const [picked, setPicked] = useState<string[]>([]); const [groupCount, setGroupCount] = useState(6);
  const absent = useMemo(() => new Set((data.attendanceRecords ?? []).filter((item) => item.classId === classId && item.date === today() && item.status === "请假").map((item) => item.studentId)), [classId, data.attendanceRecords]);
  const candidates = students.filter((student) => !absent.has(student.id)); const selected = students.filter((student) => picked.includes(student.id));
  const groupSessions = useMemo(() => (data.classroomToolSessions ?? []).filter((session) => (session.classId ?? classId) === classId && session.kind === "临时分组" && session.groups?.length).sort((a, b) => b.createdAt - a.createdAt), [classId, data.classroomToolSessions]);
  const [historyId, setHistoryId] = useState("");
  const latestSession = groupSessions.find((session) => session.id === historyId) ?? groupSessions[0];
  function draw() { const pool = candidates.filter((student) => !picked.includes(student.id)); const student = pool[Math.floor(Math.random() * pool.length)]; if (student) setPicked((ids) => [...ids, student.id]); }
  function makeGroups() { setHistoryId(""); const shuffled = [...candidates]; for (let index = shuffled.length - 1; index > 0; index -= 1) { const target = Math.floor(Math.random() * (index + 1)); [shuffled[index], shuffled[target]] = [shuffled[target], shuffled[index]]; } const groups = Array.from({ length: Math.max(2, Math.min(12, groupCount)) }, () => [] as string[]); shuffled.forEach((student, index) => groups[index % groups.length].push(student.id)); update((current) => ({ ...current, classroomToolSessions: [{ id: makeId("tool-session"), classId, date: today(), kind: "临时分组", selectedStudentIds: shuffled.map((student) => student.id), groups, createdAt: Date.now() }, ...(current.classroomToolSessions ?? [])] })); }
  async function copyGroups(session: NonNullable<typeof latestSession>) {
    const text = (session.groups ?? []).map((group, index) => `第${index + 1}组：${group.map((id) => students.find((student) => student.id === id)?.name ?? "已移除学生").join("、") || "暂无学生"}`).join("\n");
    await copyTextToClipboard(text, "已复制分组结果");
  }
  const complete = candidates.length > 0 && picked.length >= candidates.length;
  return <div className="classroom-tools"><WorkbenchPageHeader icon="🎲" tone="iris" title="课堂工具" description="随机点名与临时分组默认不写入积分，也不会形成学生评价。" /><section><header><h2>随机点名</h2><span>已排除 {absent.size} 名当天请假学生</span></header><div className="tool-draw"><button className="primary" type="button" onClick={draw} disabled={!candidates.length || complete}>随机抽取</button><button type="button" onClick={() => setPicked([])}>重置本轮</button>{selected.map((student, index) => <article key={`${student.id}-${index}`}><b>{student.name}</b><span>第 {index + 1} 次</span></article>)}{!selected.length && <p>本轮尚未抽取；被抽到的学生会暂时避开，直到重置本轮。</p>}{complete && <p>本轮所有可参与学生均已抽到，请重置后开始下一轮。</p>}</div></section><section><header><div><h2>临时分组</h2><span>按当前班级的在校学生随机分组，结果会保留在本页</span></div><span>{latestSession ? `${historyId ? "历史记录" : "最近一次"}：${latestSession.date}` : "尚未生成"}</span></header><div className="tool-groups"><label><span>分组数</span><input type="number" min="2" max="12" value={groupCount} onChange={(event) => setGroupCount(Math.max(2, Math.min(12, Number(event.target.value) || 2)))} /></label><button className="primary" type="button" onClick={makeGroups} disabled={!candidates.length}>生成分组</button></div>{latestSession ? <div className="tool-group-results" aria-live="polite"><header><div><b>{historyId ? "历史分组结果" : "最近一次分组结果"}</b><span>{latestSession.groups?.length ?? 0} 组 · {latestSession.selectedStudentIds.length} 人 · {latestSession.date}</span></div><button type="button" onClick={() => void copyGroups(latestSession)}>复制分组</button></header><div className="tool-group-grid">{(latestSession.groups ?? []).map((group, index) => <article key={`${latestSession.id}-${index}`}><header><b>第{index + 1}组</b><span>{group.length}人</span></header><ol>{group.map((id) => <li key={id}>{students.find((student) => student.id === id)?.name ?? "已移除学生"}</li>)}</ol></article>)}</div>{groupSessions.length > 1 && <details className="tool-group-history"><summary>查看历史分组（{groupSessions.length - 1} 次）</summary>{historyId && <button type="button" onClick={() => setHistoryId("")}>返回最近一次</button>}<div>{groupSessions.slice(1, 6).map((session) => <button type="button" key={session.id} onClick={() => setHistoryId(session.id)}>{session.date} · {session.groups?.length ?? 0} 组 · {session.selectedStudentIds.length} 人</button>)}</div></details>}</div> : <p className="tool-group-empty">点击“生成分组”后，这里会显示每组学生，可直接核对或复制。</p>}</section></div>;
}
